// Real recorded guitar/drums. See credits.html for sources, licenses and edits.
export class Sound {
  constructor(){this.enabled=true;this.ctx=null;this.buffers={};this.nodes=new Set();this.events=[];this.ready=null;this.motion=[];}
  async unlock(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();const c=this.ctx;this.master=c.createGain();this.master.gain.value=.68;const hp=c.createBiquadFilter();hp.type='highpass';hp.frequency.value=38;const lp=c.createBiquadFilter();lp.type='lowpass';lp.frequency.value=6700;const compressor=c.createDynamicsCompressor();compressor.threshold.value=-13;compressor.knee.value=8;compressor.ratio.value=5;compressor.attack.value=.003;compressor.release.value=.09;this.analyser=c.createAnalyser();this.analyser.fftSize=512;this.master.connect(hp).connect(lp).connect(compressor).connect(this.analyser).connect(c.destination);}if(this.ctx.state!=='running')await this.ctx.resume();}
  async preload(){await this.unlock();if(this.ready)return this.ready;this.ready=Promise.all(['low-e-down','low-e-up','kick','snare','hh','crash','tom-high','tom-mid','tom-low'].map(async name=>{const response=await fetch(new URL('./samples/'+name+'.wav?v=ankle-9',import.meta.url));if(!response.ok)throw new Error('Missing recorded sample: '+name);this.buffers[name]=await this.ctx.decodeAudioData(await response.arrayBuffer());}));return this.ready;}
  play(name,gain=1,delay=0){if(!this.enabled||!this.ctx||this.ctx.state!=='running'||!this.buffers[name])return;const source=this.ctx.createBufferSource(),volume=this.ctx.createGain();if(name.startsWith('low-e-')){const old=this.guitarVoice;if(old){try{old.volume.gain.cancelScheduledValues(this.ctx.currentTime);old.volume.gain.setTargetAtTime(0,this.ctx.currentTime,.004);old.source.stop(this.ctx.currentTime+.018);}catch{}}this.guitarVoice={source,volume};}source.buffer=this.buffers[name];volume.gain.value=gain;source.connect(volume).connect(this.master);this.nodes.add(source);source.onended=()=>{this.nodes.delete(source);source.disconnect();volume.disconnect();};source.start(this.ctx.currentTime+delay);if(!name.startsWith('low-e-'))this.motion.push({name,at:performance.now()+delay*1000});this.events.push(name);if(this.events.length>128)this.events.shift();}
  hit(beat,stroke,{bpm=0,hits=1,roll=0}={}){this.play(stroke<0?'low-e-down':'low-e-up',.95);this.play('kick',.82);if(beat===1||beat===5)this.play('hh',.75);if(beat===3||beat===7)this.play('snare',.75);
    if(bpm>=120){if(beat===0)this.play('crash',.48);if(Math.floor((hits-1)/8)%4===3&&beat>=4&&beat<=6)this.play(['tom-high','tom-mid','tom-low'][beat-4],.80);}
    if(roll>.025){const interval=Math.max(.02,Math.min(.35,15/Math.max(150,bpm)));this.play('kick',.72*roll,interval*.5);if(beat!==3&&beat!==7)this.play('snare',.50*roll);this.play('snare',.47*roll,interval*.5);}
  }
  success(){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime;for(const [i,note] of[64,67,71,76].entries()){const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type='triangle';osc.frequency.value=440*2**((note-69)/12);gain.gain.setValueAtTime(0,t+i*.12);gain.gain.linearRampToValueAtTime(.12,t+i*.12+.008);gain.gain.exponentialRampToValueAtTime(.001,t+i*.12+.42);osc.connect(gain).connect(this.master);this.nodes.add(osc);osc.onended=()=>{this.nodes.delete(osc);osc.disconnect();gain.disconnect();};osc.start(t+i*.12);osc.stop(t+i*.12+.45);}}
  level(){if(!this.analyser)return 0;const d=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(d);return Math.sqrt(d.reduce((s,v)=>s+v*v,0)/d.length);}
  stop(){for(const source of this.nodes){try{source.stop();}catch{}}this.nodes.clear();this.guitarVoice=null;this.motion.length=0;}
  dispose(){this.stop();this.ctx?.close();}
}
