// Original synthesized riff notes and drums; no borrowed recordings.
export class Sound {
  constructor(){this.enabled=true;this.ctx=null;this.buffers={};this.nodes=new Set();this.events=[];this.ready=null;}
  async unlock(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();const c=this.ctx;this.master=c.createGain();this.master.gain.value=.68;const hp=c.createBiquadFilter();hp.type='highpass';hp.frequency.value=38;const lp=c.createBiquadFilter();lp.type='lowpass';lp.frequency.value=6700;const compressor=c.createDynamicsCompressor();compressor.threshold.value=-13;compressor.knee.value=8;compressor.ratio.value=5;compressor.attack.value=.003;compressor.release.value=.09;this.analyser=c.createAnalyser();this.analyser.fftSize=512;this.master.connect(hp).connect(lp).connect(compressor).connect(this.analyser).connect(c.destination);}if(this.ctx.state!=='running')await this.ctx.resume();}
  async preload(){await this.unlock();if(this.ready)return this.ready;this.ready=(async()=>{for(const midi of[40,43,45,46])this.buffers['g'+midi]=await this.guitar(midi);this.buffers.kick=this.drum('kick');this.buffers.hh=this.drum('hh');this.buffers.snare=this.drum('snare');})();return this.ready;}
  async guitar(midi){const rate=44100,len=Math.floor(rate*.29),freq=440*2**((midi-69)/12),offline=new OfflineAudioContext(1,len,rate);const buffer=offline.createBuffer(1,len,rate),data=buffer.getChannelData(0);let seed=17+midi;const noise=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2147483648-1;};const delay=Math.round(rate/freq),strings=[new Float32Array(delay),new Float32Array(Math.round(delay/1.498))];for(const string of strings)for(let j=0;j<string.length;j++)string[j]=noise()*.9;const pos=[0,0];for(let i=0;i<len;i++){const t=i/rate;let sample=0;for(let j=0;j<2;j++){const string=strings[j],p=pos[j];sample+=string[p]*(j?.55:1);string[p]=(string[p]+string[(p+1)%string.length])*.493;pos[j]=(p+1)%string.length;}const env=Math.min(1,t/.002)*Math.exp(-t*11)*Math.min(1,(.29-t)/.035);data[i]=sample*env*.70+noise()*.09*Math.exp(-t*95);}
    const source=offline.createBufferSource();source.buffer=buffer;const distortion=offline.createWaveShaper(),curve=new Float32Array(4096);for(let i=0;i<curve.length;i++){const x=i/(curve.length-1)*2-1;curve[i]=Math.tanh(x*8)*.72;}distortion.curve=curve;distortion.oversample='2x';const hp=offline.createBiquadFilter();hp.type='highpass';hp.frequency.value=85;const mid=offline.createBiquadFilter();mid.type='peaking';mid.frequency.value=800;mid.Q.value=.9;mid.gain.value=-4;const lp=offline.createBiquadFilter();lp.type='lowpass';lp.frequency.value=4400;source.connect(distortion).connect(hp).connect(mid).connect(lp).connect(offline.destination);source.start();return offline.startRendering();
  }
  drum(kind){const c=this.ctx,rate=c.sampleRate,duration=kind==='kick'?.32:kind==='hh'?.095:.24,buffer=c.createBuffer(1,Math.ceil(rate*duration),rate),data=buffer.getChannelData(0);let phase=0,lastNoise=0,seed=81;for(let i=0;i<data.length;i++){const t=i/rate;seed=(seed*1664525+1013904223)>>>0;const n=seed/2147483648-1;let sample;if(kind==='kick'){phase+=2*Math.PI*(51+110*Math.exp(-t*55))/rate;sample=Math.sin(phase)*Math.exp(-t*17)*.85+(n-lastNoise)*.085*Math.exp(-t*100);}else if(kind==='snare'){sample=(n-lastNoise)*.25*Math.exp(-t*20)+Math.sin(t*2*Math.PI*185)*.29*Math.exp(-t*28);}else sample=(n-lastNoise)*.16*Math.exp(-t*50);lastNoise=n;data[i]=sample*Math.min(1,t/.001)*Math.min(1,(duration-t)/.018);}return buffer;}
  play(name,gain=1){if(!this.enabled||!this.ctx||this.ctx.state!=='running'||!this.buffers[name])return;const source=this.ctx.createBufferSource(),volume=this.ctx.createGain();source.buffer=this.buffers[name];volume.gain.value=gain;source.connect(volume).connect(this.master);this.nodes.add(source);source.onended=()=>{this.nodes.delete(source);source.disconnect();volume.disconnect();};source.start();this.events.push(name);if(this.events.length>128)this.events.shift();}
  hit(beat){this.play('g'+[40,40,43,40,46,45,43,40][beat],.65);this.play('kick',.68);if(beat===1||beat===5)this.play('hh',.75);if(beat===3||beat===7)this.play('snare',.75);}
  success(){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime;for(const [i,note] of[64,67,71,76].entries()){const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type='triangle';osc.frequency.value=440*2**((note-69)/12);gain.gain.setValueAtTime(0,t+i*.12);gain.gain.linearRampToValueAtTime(.12,t+i*.12+.008);gain.gain.exponentialRampToValueAtTime(.001,t+i*.12+.42);osc.connect(gain).connect(this.master);this.nodes.add(osc);osc.onended=()=>{this.nodes.delete(osc);osc.disconnect();gain.disconnect();};osc.start(t+i*.12);osc.stop(t+i*.12+.45);}}
  level(){if(!this.analyser)return 0;const d=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(d);return Math.sqrt(d.reduce((s,v)=>s+v*v,0)/d.length);}
  stop(){for(const source of this.nodes){try{source.stop();}catch{}}this.nodes.clear();}
  dispose(){this.stop();this.ctx?.close();}
}
