import {T,build} from './models.js?v=ankle-3';
import {Sound} from './audio.js?v=ankle-3';
const $=id=>document.getElementById(id),sound=new Sound(),rig=build();
const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('scene').append(renderer.domElement);
const camera=new T.PerspectiveCamera(43,1,.1,40),state={mode:'menu',hits:0,beat:-1,taps:[],speed:0,bpm:0,stroke:-1,peak:0,stress:0,start:0,last:0,ended:0,elapsed:0};let previous=performance.now(),punchAt=-100,hhAt=-100,snareAt=-100,disposed=false;const beatEls=[...document.querySelectorAll('[data-beat]')],particles=[];
const effects=$('confetti'),fx=effects.getContext('2d');
function resize(){const area=$('scene'),w=area.clientWidth,h=area.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;const narrow=w/h<.7;camera.position.set(.8,2.75,narrow?8.1:7.2);camera.lookAt(0,1.10,-.45);camera.updateProjectionMatrix();effects.width=$('scene').parentElement.clientWidth;effects.height=$('scene').parentElement.clientHeight;}
new ResizeObserver(resize).observe($('scene'));resize();
function showBest(){try{const best=JSON.parse(localStorage.getItem('qaf-ankle-bpm-best'));if(best)$('best').textContent=`最佳手速 ${Math.round(best.peak)} BPM · 最快完成 ${best.seconds.toFixed(1)} 秒`;}catch{}}
function updateHUD(){ $('speed').textContent=Math.round(state.bpm);$('hits').textContent=state.hits;$('stress').style.width=state.stress+'%';$('stress-value').textContent=Math.round(state.stress)+'%';$('condition').textContent=state.stress>75?'腳踝快不行了':state.bpm>150?'全力跟上！':state.speed>0?'繼續加速':'暖身中';}
async function start(){if($('start').disabled||state.mode==='play')return;$('start').disabled=true;$('again').disabled=true;$('start').textContent='音色準備中…';try{await sound.preload();sound.stop();Object.assign(state,{mode:'play',hits:0,beat:-1,taps:[],speed:0,bpm:0,stroke:-1,peak:0,stress:0,start:performance.now(),last:0,ended:0,elapsed:0});punchAt=hhAt=snareAt=-100;particles.length=0;rig.stars.visible=false;rig.drummer.rotation.z=0;rig.mouth.scale.y=1;$('menu').hidden=true;$('end').hidden=true;$('pick').disabled=false;beatEls.forEach(el=>el.classList.remove('active'));$('speech').textContent='你先彈，我一定跟得上。';updateHUD();window.QAFPlayCount?.start('ankle-breaker');}catch(e){$('best').textContent='音訊未準備好，請再按一次開始。';sound.ready=null;console.error(e);}finally{$('start').disabled=false;$('again').disabled=false;$('start').textContent='開始練團 →';}}
function tempo(now){const points=state.taps;if(points.length<3)return 0;const span=points.at(-1)-points[0];const mean=span/(points.length-1),idle=now-points.at(-1);if(idle>Math.max(650,mean*1.7))return 0;return Math.min(900,60000/Math.max(mean,idle));}
function pick(){if(state.mode!=='play'||document.hidden)return;if(sound.ctx?.state!=='running')sound.unlock();const now=performance.now();state.hits++;state.beat=(state.beat+1)%8;state.stroke=state.hits%2?-1:1;state.last=now;state.taps.push(now);state.taps=state.taps.filter(t=>now-t<4000).slice(-9);state.bpm=tempo(now);state.speed=state.bpm/60;state.peak=Math.max(state.peak,state.bpm);sound.hit(state.beat,state.stroke);punchAt=now;if(state.beat===1||state.beat===5)hhAt=now;if(state.beat===3||state.beat===7)snareAt=now;beatEls.forEach((el,i)=>el.classList.toggle('active',i===state.beat));$('pick').dataset.stroke=state.stroke<0?'left':'right';$('pick').classList.add('pressed');updateHUD();}
function win(now){if(state.mode!=='play')return;state.mode='injured';state.ended=now;state.elapsed=(now-state.start)/1000;$('pick').disabled=true;$('speech').textContent='啊！我的腳踝！今天練團到這裡！';rig.stars.visible=true;sound.stop();sound.success();for(let i=0;i<95;i++)particles.push({x:effects.width*.5,y:effects.height*.42,vx:(Math.random()-.5)*260,vy:-100-Math.random()*190,rot:Math.random()*6,spin:(Math.random()-.5)*7,color:['#e6b46f','#b082a1','#7babb1','#ded4b3'][i%4]});try{const prior=JSON.parse(localStorage.getItem('qaf-ankle-bpm-best')||'null');localStorage.setItem('qaf-ankle-bpm-best',JSON.stringify({peak:Math.max(prior?.peak||0,state.peak),seconds:Math.min(prior?.seconds||Infinity,state.elapsed)}));}catch{}showBest();}
function animate(now){if(disposed)return;requestAnimationFrame(animate);const dt=Math.min((now-previous)/1000,.05);previous=now;if(state.mode==='play'){state.taps=state.taps.filter(t=>now-t<4000).slice(-9);state.bpm=tempo(now);state.speed=state.bpm/60;const increase=state.bpm>150?20:-12;state.stress=T.MathUtils.clamp(state.stress+increase*dt,0,100);if(state.stress>=100&&state.hits>=16)win(now);else if(state.stress>75)$('speech').textContent='慢一點！我的腳快打結了！';else if(state.stress>35)$('speech').textContent='大鼓跟上！不要停！';else if(now-state.last>1600&&state.hits)$('speech').textContent='呼，休息一下……再來！';updateHUD();}
 const hitAge=(now-punchAt)/1000,hhAge=(now-hhAt)/1000,snareAge=(now-snareAt)/1000,pulse=hitAge<.18?Math.sin(hitAge/.18*Math.PI):0;
 rig.pickHand.position.y=-.07-pulse*.09*state.stroke;rig.pickHand.rotation.z=pulse*.27*state.stroke;rig.fretHand.position.y=1.12;rig.kick.scale.set(1+pulse*.025,1+pulse*.025,1);
 rig.head.rotation.z=Math.sin(now*.003)*.025+Math.sin(now*.008)*pulse*.08;
 rig.arms[0].rotation.x=(hhAge<.20?Math.sin(hhAge/.20*Math.PI):0)*-.55;rig.arms[1].rotation.x=(snareAge<.21?Math.sin(snareAge/.21*Math.PI):0)*-.65;rig.hh.rotation.z=hhAge<.30?Math.sin(hhAge*70)*.06*(1-hhAge/.3):0;
 for(let i=0;i<2;i++)rig.feet[i].rotation.x=-pulse*(i===state.hits%2?.42:.16);
 if(state.mode==='injured'||state.mode==='end'){const age=(now-state.ended)/1000;rig.drummer.rotation.z=-.15*Math.min(1,age*2);rig.head.rotation.z=-.15+Math.sin(now*.004)*.05;rig.feet[0].rotation.z=-.65*Math.min(1,age*3);rig.feet[0].position.y=.17+.18*Math.min(1,age*3);rig.mouth.scale.y=4;rig.arms[1].rotation.x=.8;rig.stars.rotation.y=now*.0018;for(const child of rig.stars.children)child.rotation.y=-rig.stars.rotation.y;if(age>2.8&&state.mode==='injured'){state.mode='end';$('result').textContent=`完成時間 ${state.elapsed.toFixed(1)} 秒 · 出手 ${state.hits} 下 · 最高 ${Math.round(state.peak)} BPM`;$('end').hidden=false;}}
 else {for(const foot of rig.feet){foot.position.y=.17;foot.rotation.z=0;}}
 fx.clearRect(0,0,effects.width,effects.height);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt;p.rot+=p.spin*dt;fx.save();fx.translate(p.x,p.y);fx.rotate(p.rot);fx.fillStyle=p.color;fx.fillRect(-3,-2,6,4);fx.restore();if(p.y>effects.height+20)particles.splice(i,1);}renderer.render(rig.scene,camera);
}
$('start').onclick=start;$('again').onclick=start;$('pick').addEventListener('pointerdown',event=>{event.preventDefault();pick();});window.addEventListener('pointerup',()=> $('pick').classList.remove('pressed'));window.addEventListener('pointercancel',()=> $('pick').classList.remove('pressed'));window.addEventListener('keydown',event=>{if((event.code==='Space'||event.code==='Enter')&&state.mode==='play'&&event.target.tagName!=='A'&&event.target.id!=='sound'){event.preventDefault();if(!event.repeat)pick();}});window.addEventListener('keyup',()=> $('pick').classList.remove('pressed'));
$('sound').onclick=async()=>{await sound.unlock();sound.enabled=!sound.enabled;if(!sound.enabled)sound.stop();$('sound').textContent='音效 '+(sound.enabled?'ON':'OFF');};document.addEventListener('contextmenu',event=>event.preventDefault());document.addEventListener('selectstart',event=>event.preventDefault());document.addEventListener('dragstart',event=>event.preventDefault());document.addEventListener('visibilitychange',()=>{sound.stop();state.taps=[];state.speed=0;state.bpm=0;});
function dispose(){if(disposed)return;disposed=true;sound.dispose();renderer.dispose();}window.addEventListener('pagehide',dispose);document.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>sound.stop()));
window.ankleGame={state,sound,pick,rig};showBest();$('loading').hidden=true;requestAnimationFrame(animate);
