const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let f=path.join(root,req.url.split('?')[0]);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(f)]||'text/plain');fs.createReadStream(f).pipe(res);});
server.listen(8134,'127.0.0.1',async()=>{let browser;try{browser=await chromium.launch({headless:true,channel:'msedge'});const c=await browser.newContext({viewport:{width:390,height:740},isMobile:true,hasTouch:true});let writes=0;const svg='<svg xmlns="http://www.w3.org/2000/svg"><title>plays: resource not found</title></svg>';await c.route('https://hits.sh/**',r=>{writes++;return r.fulfill({body:'<svg xmlns="http://www.w3.org/2000/svg"/>',contentType:'image/svg+xml'});});await c.route('https://img.shields.io/**',r=>r.fulfill({body:svg,contentType:'image/svg+xml'}));const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8134/ankle-breaker/');await p.waitForFunction(()=>window.ankleGame);assert.equal(writes,0);await p.screenshot({path:path.join(__dirname,'qa-menu.png')});await p.click('#start');await p.waitForFunction(()=>ankleGame.state.mode==='play');assert.equal(writes,1);
 for(const bpm of [149,150,151]){await p.evaluate(bpm=>{const now=performance.now(),gap=15000/bpm;Object.assign(ankleGame.state,{stress:10,taps:[now-2*gap,now-gap,now]});},bpm);await p.waitForTimeout(45);const stress=await p.evaluate(()=>ankleGame.state.stress);if(bpm<=150)assert(stress<10,`Must not accumulate at ${bpm} BPM: ${stress}`);else assert(stress>10,`Must accumulate above 150 BPM: ${stress}`);}await p.evaluate(()=>Object.assign(ankleGame.state,{stress:0,taps:[],bpm:0,speed:0,roll:0}));

 for(let i=0;i<8;i++){await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1,clientX:i%2?350:40});await p.waitForTimeout(155);}
 const rhythm=await p.evaluate(()=>ankleGame.sound.events);assert.equal(rhythm.filter(v=>v==='kick').length,8);assert.equal(rhythm.filter(v=>v==='hh').length,2);assert.equal(rhythm.filter(v=>v==='snare').length,2);assert.deepEqual(rhythm,['low-e-down','kick','low-e-up','kick','hh','low-e-down','kick','low-e-up','kick','snare','low-e-down','kick','low-e-up','kick','hh','low-e-down','kick','low-e-up','kick','snare']);
 await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});let rms=await p.evaluate(()=>ankleGame.sound.level());if(rms===0){await p.waitForTimeout(25);rms=await p.evaluate(()=>ankleGame.sound.level());}assert(rms>.005,'Real audio signal missing');await p.waitForTimeout(1200);const count=await p.evaluate(()=>ankleGame.state.hits);assert.equal(count,9);assert.equal(await p.evaluate(()=>ankleGame.state.speed),0);
 await p.screenshot({path:path.join(__dirname,'qa-playing.png')});await p.evaluate(()=>{document.getElementById('speech').style.visibility='hidden';});await p.locator('#scene').screenshot({path:path.join(__dirname,'cover.png')});await p.evaluate(()=>document.getElementById('speech').style.visibility='');
 const adaptive=await p.evaluate(()=>{const s=ankleGame.sound;function run(bpm,roll,n){s.stop();s.events=[];for(let i=0;i<n;i++)s.hit(i%8,i%2?1:-1,{bpm,hits:i+1,roll});return [...s.events];}const quiet=run(119,0,32),fast=run(120,0,32),roll=run(150,1,8);s.stop();s.events=[];return {quiet,fast,roll,duration:s.buffers['low-e-down'].duration};});assert(!adaptive.quiet.includes('crash'));assert(!adaptive.quiet.includes('tom-high'));assert.equal(adaptive.fast.filter(x=>x==='crash').length,4);for(const t of ['tom-high','tom-mid','tom-low'])assert.equal(adaptive.fast.filter(x=>x===t).length,1);assert.equal(adaptive.roll.filter(x=>x==='kick').length,16);assert.equal(adaptive.roll.filter(x=>x==='snare').length,16);assert(adaptive.duration<.25);
 const pad=await p.locator('#pick').boundingBox();assert.equal(pad.width,390);assert(pad.height>=100);for(const [x,side] of [[10,'left'],[15,'left'],[375,'right'],[380,'right']]){await p.touchscreen.tap(x,pad.y+40);assert.equal(await p.evaluate(()=>document.getElementById('pick').dataset.stroke),side);}const session=await c.newCDPSession(p),beforeTouch=await p.evaluate(()=>ankleGame.state.hits);const l={x:40,y:pad.y+55,id:1},r={x:350,y:pad.y+55,id:2};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[l]});await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[l,r]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[r]});for(let i=0;i<10;i++){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[l,r]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[r]});}await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.evaluate(()=>ankleGame.state.hits),beforeTouch+12);await p.evaluate(()=>Object.assign(ankleGame.state,{hits:9,taps:[],bpm:0,stress:0,roll:0}));
 assert.equal(await p.evaluate(()=>Object.keys(ankleGame.sound.buffers).length),9);for(const id of ['pick-left','pick-right','pick-left','pick-right']){await p.locator('#'+id).dispatchEvent('pointerdown',{pointerId:id==='pick-left'?1:2,clientX:id==='pick-left'?40:350});}assert.equal(await p.evaluate(()=>ankleGame.state.hits),13);assert.equal(await p.evaluate(()=>document.getElementById('pick').dataset.stroke),'right');await p.waitForTimeout(4500);for(let i=0;i<80;i++){if(await p.evaluate(()=>ankleGame.state.mode!=='play'))break;await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});await p.waitForTimeout(88);}
 await p.waitForFunction(()=>ankleGame.state.mode==='end');assert(await p.evaluate(()=>ankleGame.state.peak>=149));assert(await p.locator('#end').isVisible());assert.equal(await p.locator('#peak-speed').textContent(),await p.evaluate(()=>ankleGame.state.peak.toFixed(1)));assert(await p.evaluate(()=>ankleGame.rig.stars.visible));assert(await p.evaluate(()=>ankleGame.rig.feet[0].rotation.z<-.5));await p.screenshot({path:path.join(__dirname,'qa-end.png')});await p.click('#again');await p.waitForFunction(()=>ankleGame.state.mode==='play');assert.equal(writes,2);assert.equal(await p.evaluate(()=>ankleGame.state.hits),0);
 await p.click('#sound');await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>ankleGame.sound.nodes.size),0);await p.click('#sound');await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});await p.waitForTimeout(25);assert(await p.evaluate(()=>ankleGame.sound.level())>.005);await p.click('#exit');assert(p.url().endsWith('/'));
 await p.goto('http://127.0.0.1:8134/?embed=friend');assert.equal(await p.locator('.friend-card').count(),4);await p.getByRole('button',{name:/腳踝終結者/}).click();const f=p.frameLocator('.friend-screen iframe');await f.locator('#menu .home').waitFor();await f.locator('#menu .home').click();assert(await p.locator('.friend-catalogue').isVisible());
 for(const size of [{width:320,height:568},{width:430,height:932}]){await p.setViewportSize(size);await p.goto('http://127.0.0.1:8134/ankle-breaker/');await p.waitForFunction(()=>window.ankleGame);await p.locator('#start').scrollIntoViewIfNeeded();assert(await p.locator('#start').isVisible());assert(await p.locator('#menu .home').isVisible());assert.equal(await p.evaluate(()=>getComputedStyle(document.body).userSelect),'none');await p.click('#start');await p.waitForFunction(()=>ankleGame.state.mode==='play');const bb=await p.locator('#pick').boundingBox();assert(bb.y+bb.height<=size.height);assert.equal(bb.width,size.width);await p.screenshot({path:path.join(__dirname,'qa-mobile-'+size.width+'.png')});const clearance=await p.evaluate(()=>{const {rig,camera}=ankleGame;camera.updateMatrixWorld();rig.head.updateWorldMatrix(true,true);const pos=rig.head.position.clone();rig.head.getWorldPosition(pos);pos.x-=.4;pos.project(camera);const scene=document.getElementById('scene').getBoundingClientRect(),speech=document.getElementById('speech').getBoundingClientRect(),header=document.querySelector('header').getBoundingClientRect();return {headLeft:scene.left+(pos.x+1)*scene.width/2,speechRight:speech.right,speechTop:speech.top,headerBottom:header.bottom};});assert(clearance.speechRight<clearance.headLeft,JSON.stringify(clearance));assert(clearance.speechTop>clearance.headerBottom,JSON.stringify(clearance));assert(bb.height>=100);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),size.width);}
 assert.deepEqual(errors,[]);console.log('ANKLE_QA_PASS',{rms,writes,checks:['exact eight-beat voices','tap only','win at sustained speed','replay reset','mute/unmute','real output','mobile layouts','four-card embed exit'],errors});
}catch(e){console.error(e);process.exitCode=1;}finally{await browser?.close();server.close();}});
