const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let f=path.join(root,req.url.split('?')[0]);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(f)]||'text/plain');fs.createReadStream(f).pipe(res);});
server.listen(8134,'127.0.0.1',async()=>{let browser;try{browser=await chromium.launch({headless:true,channel:'msedge'});const c=await browser.newContext({viewport:{width:390,height:740},isMobile:true,hasTouch:true});let writes=0;const svg='<svg xmlns="http://www.w3.org/2000/svg"><title>plays: resource not found</title></svg>';await c.route('https://hits.sh/**',r=>{writes++;return r.fulfill({body:'<svg xmlns="http://www.w3.org/2000/svg"/>',contentType:'image/svg+xml'});});await c.route('https://img.shields.io/**',r=>r.fulfill({body:svg,contentType:'image/svg+xml'}));const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8134/ankle-breaker/');await p.waitForFunction(()=>window.ankleGame);assert.equal(writes,0);await p.screenshot({path:path.join(__dirname,'qa-menu.png')});await p.click('#start');await p.waitForFunction(()=>ankleGame.state.mode==='play');assert.equal(writes,1);
 for(let i=0;i<8;i++){await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});await p.waitForTimeout(110);}
 const rhythm=await p.evaluate(()=>ankleGame.sound.events);assert.equal(rhythm.filter(v=>v==='kick').length,8);assert.equal(rhythm.filter(v=>v==='hh').length,2);assert.equal(rhythm.filter(v=>v==='snare').length,2);assert.deepEqual(rhythm,['g40','kick','g40','kick','hh','g43','kick','g40','kick','snare','g46','kick','g45','kick','hh','g43','kick','g40','kick','snare']);
 await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});let rms=await p.evaluate(()=>ankleGame.sound.level());if(rms===0){await p.waitForTimeout(25);rms=await p.evaluate(()=>ankleGame.sound.level());}assert(rms>.005,'Real audio signal missing');await p.waitForTimeout(1200);const count=await p.evaluate(()=>ankleGame.state.hits);assert.equal(count,9);assert.equal(await p.evaluate(()=>ankleGame.state.speed),0);
 await p.screenshot({path:path.join(__dirname,'qa-playing.png')});await p.evaluate(()=>{document.getElementById('speech').style.visibility='hidden';});await p.locator('#scene').screenshot({path:path.join(__dirname,'cover.png')});await p.evaluate(()=>document.getElementById('speech').style.visibility='');
 for(let i=0;i<80;i++){if(await p.evaluate(()=>ankleGame.state.mode!=='play'))break;await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});await p.waitForTimeout(145);}
 await p.waitForFunction(()=>ankleGame.state.mode==='end');assert(await p.locator('#end').isVisible());assert(await p.evaluate(()=>ankleGame.rig.stars.visible));assert(await p.evaluate(()=>ankleGame.rig.feet[0].rotation.z<-.5));await p.screenshot({path:path.join(__dirname,'qa-end.png')});await p.click('#again');await p.waitForFunction(()=>ankleGame.state.mode==='play');assert.equal(writes,2);assert.equal(await p.evaluate(()=>ankleGame.state.hits),0);
 await p.click('#sound');await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>ankleGame.sound.nodes.size),0);await p.click('#sound');await p.locator('#pick').dispatchEvent('pointerdown',{pointerId:1});await p.waitForTimeout(25);assert(await p.evaluate(()=>ankleGame.sound.level())>.005);await p.click('#exit');assert(p.url().endsWith('/'));
 await p.goto('http://127.0.0.1:8134/?embed=friend');assert.equal(await p.locator('.friend-card').count(),4);await p.getByRole('button',{name:/腳踝終結者/}).click();const f=p.frameLocator('.friend-screen iframe');await f.locator('#menu .home').waitFor();await f.locator('#menu .home').click();assert(await p.locator('.friend-catalogue').isVisible());
 for(const size of [{width:320,height:568},{width:430,height:932}]){await p.setViewportSize(size);await p.goto('http://127.0.0.1:8134/ankle-breaker/');await p.waitForFunction(()=>window.ankleGame);await p.locator('#start').scrollIntoViewIfNeeded();assert(await p.locator('#start').isVisible());assert(await p.locator('#menu .home').isVisible());assert.equal(await p.evaluate(()=>getComputedStyle(document.body).userSelect),'none');await p.click('#start');await p.waitForFunction(()=>ankleGame.state.mode==='play');const bb=await p.locator('#pick').boundingBox();assert(bb.y+bb.height<=size.height);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),size.width);}
 assert.deepEqual(errors,[]);console.log('ANKLE_QA_PASS',{rms,writes,checks:['exact eight-beat voices','tap only','win at sustained speed','replay reset','mute/unmute','real output','mobile layouts','four-card embed exit'],errors});
}catch(e){console.error(e);process.exitCode=1;}finally{await browser?.close();server.close();}});
