// Original synthesized arpeggios; all voices are preloaded and decoded before use.
const progressions=[[[52,59,64,67],[55,62,67,71],[50,57,62,66],[45,52,57,60]],[[45,52,57,60],[48,55,60,64],[55,62,67,71],[53,60,65,69]],[[50,57,62,65],[53,60,65,69],[48,55,60,64],[55,62,67,71]],[[47,54,59,62],[50,57,62,66],[45,52,57,61],[52,59,64,68]],[[55,62,67,71],[53,60,65,69],[48,55,60,64],[50,57,62,65]]];
const riffs=[[0,1,2,1,3,2,1,2],[0,2,1,3,2,1,0,3],[0,1,0,2,3,2,1,3],[2,0,1,2,3,1,2,3],[0,2,3,1,2,3,2,1]];
export class Sound{
 constructor(){this.enabled=true;this.sources=new Set();this.buffers={};this.token=0;this.until=0;}
 async unlock(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.out=this.ctx.createGain();this.out.gain.value=.72;this.compressor=this.ctx.createDynamicsCompressor();this.compressor.threshold.value=-13;this.compressor.ratio.value=3;this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=1024;this.out.connect(this.compressor).connect(this.analyser).connect(this.ctx.destination);const silent=this.ctx.createBufferSource();silent.buffer=this.ctx.createBuffer(1,1,this.ctx.sampleRate);silent.connect(this.out);silent.start();}if(this.ctx.state!=='running')await this.ctx.resume();return this.ctx;}
 async preload(){await this.unlock();if(!this.ready)this.ready=Promise.all(['male','female'].flatMap(g=>['high','low','good'].map(async k=>{const key=g+'-'+k;const response=await fetch(new URL('./audio/'+key+'.mp3?v=nut-4',import.meta.url));if(!response.ok)throw Error('語音載入失敗');this.buffers[key]=await this.ctx.decodeAudioData(await response.arrayBuffer());})));return this.ready;}
 track(s){this.sources.add(s);s.onended=()=>this.sources.delete(s);return s;}
 stop(){this.token++;for(const s of this.sources){try{s.stop();}catch{}}this.sources.clear();this.until=0;this.grinding=null;}
 async voice(female,kind){const token=this.token;await this.preload();if(token!==this.token||!this.enabled)return 0;await this.unlock();const b=this.buffers[(female?'female':'male')+'-'+kind],s=this.track(this.ctx.createBufferSource());s.buffer=b;const gain=this.ctx.createGain();gain.gain.value=.62;s.connect(gain).connect(this.out);s.start();return b.duration;}
 pluck(midi,start,quality){const c=this.ctx,f=440*2**((midi-69)/12),n=Math.floor(c.sampleRate/f),length=Math.floor(c.sampleRate*.8425),b=c.createBuffer(1,length,c.sampleRate),v=b.getChannelData(0),ring=new Float32Array(n);for(let i=0;i<n;i++)ring[i]=(Math.random()*2-1)*.58;let p=0;for(let i=0;i<length;i++){const a=ring[p],next=ring[(p+1)%n];ring[p]=(a+next)*.498;v[i]=a*Math.exp(-i/(c.sampleRate*.84));p=(p+1)%n;}let s=this.track(c.createBufferSource());s.buffer=b;let filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=quality==='high'?650:4300;let gain=c.createGain();gain.gain.value=quality==='high'?.14:.2;const drive=c.createWaveShaper(),curve=new Float32Array(512);for(let j=0;j<curve.length;j++){const x=j*2/(curve.length-1)-1;curve[j]=Math.tanh(x*2)/Math.tanh(2);}drive.curve=curve;drive.oversample='2x';s.connect(drive).connect(filter).connect(gain).connect(this.out);s.start(start);if(quality==='low'){let buzz=this.track(c.createOscillator()),bg=c.createGain(),bp=c.createBiquadFilter();buzz.type='sawtooth';buzz.frequency.value=f*1.018;bp.type='bandpass';bp.frequency.value=1100;bp.Q.value=.65;bg.gain.setValueAtTime(.018,start);bg.gain.exponentialRampToValueAtTime(.0001,start+.5);buzz.connect(bp).connect(bg).connect(this.out);buzz.start(start);buzz.stop(start+.5);}}
 music(index,quality='good',delay=0){if(!this.enabled||!this.ctx)return 0;let start=this.ctx.currentTime+.07+delay,step=.154;const part=index%5,order=riffs[part];progressions[part].forEach((ch,c)=>order.forEach((n,i)=>{const beat=start+(c*8+i)*step;this.pluck(ch[n],beat,quality);if(i===0||i===4)this.pluck(ch[1],beat+.012,quality);}));this.from=performance.now()+delay*1000+70;this.until=this.from+5800;return 5.88+delay;}
 grind(on){if(!on){if(this.grinding){try{this.grinding.stop();}catch{}}this.grinding=null;return;}if(this.grinding||!this.enabled||!this.ctx)return;let b=this.ctx.createBuffer(1,this.ctx.sampleRate,this.ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*.25;let s=this.track(this.ctx.createBufferSource());s.buffer=b;s.loop=true;let filter=this.ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=950;filter.Q.value=.6;let gain=this.ctx.createGain();gain.gain.value=.06;s.connect(filter).connect(gain).connect(this.out);s.start();this.grinding=s;}
 pop(){if(!this.enabled||!this.ctx)return;let b=this.ctx.createBuffer(1,this.ctx.sampleRate*.18,this.ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/(this.ctx.sampleRate*.035))*.15;let s=this.track(this.ctx.createBufferSource());s.buffer=b;s.connect(this.out);s.start();}
 level(){if(!this.analyser)return 0;let a=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(a);return Math.sqrt(a.reduce((v,x)=>v+x*x,0)/a.length);}
 toggle(){this.enabled=!this.enabled;if(!this.enabled)this.stop();return this.enabled;}
}
