import {T,workshop,person,inspection,updateInspection,types,customers,ball} from './models.js?v=nut-2';
import {Sound} from './audio.js?v=nut-2';
const $=id=>document.getElementById(id),sound=new Sound(),levels=[{name:'普通客人',safe:[.07,.15],pay:[500,800]},{name:'資深玩家',safe:[.075,.115],pay:[1200,2500]},{name:'超級收藏家',safe:[.085,.105],pay:[3000,5000]}];
const state={mode:'menu',stage:0,gap:.26,tested:false,filing:false,powder:false,total:0,ledger:[],kind:0,type:0,mood:0,started:0,tests:0,reworks:0,usedTunes:[],epoch:0};
const scene=new T.Scene();workshop(scene);const camera=new T.PerspectiveCamera(43,1,.1,40),renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.domElement.setAttribute('aria-label','立體吉他與維修工具');$('scene').append(renderer.domElement);let customer=person(0,1);customer.position.set(1.65,0,.7);scene.add(customer);const neck=inspection();scene.add(neck);const wide=new T.Vector3(4.4,3.6,7.1),close=new T.Vector3(-.2,2.65,8.8),wideTarget=new T.Vector3(.6,2,0),closeTarget=new T.Vector3(-.2,2.5,.6),look=wideTarget.clone();camera.position.copy(wide);camera.lookAt(look);let fireworks=[],last=performance.now(),celebrationAt=0,transition=0,dragId=null,flyingGuitar=null;
function hide(id,value){$(id).hidden=value;}
function say(text){$('speech').textContent=text;}
function range(){const l=levels[state.stage];return l.safe;}
function quality(){const [a,b]=range();return state.gap<a?'low':state.gap>b?'high':'good';}
function controls(mode){hide('customer-controls',mode!=='customer');hide('repair-controls',mode!=='repair');hide('result-controls',mode!=='result');$('labels').style.display=mode==='repair'?'block':'none';hide('gauge',mode!=='repair');neck.visible=mode==='repair';customer.userData.held.visible=mode!=='repair';}
function refresh(){const [a,b]=range();$('stage-label').textContent=`委託 ${state.stage+1} / 3 · ${levels[state.stage].name}`;$('customer-label').textContent=customers[state.kind]+' · '+types[state.type];$('cash').textContent='收入 $'+state.total.toLocaleString();$('range').textContent=state.mode==='repair'?`合格弦隙 ${a.toFixed(3)}–${b.toFixed(3)} mm`:'先聽聲音，再決定磨低或補槽。';$('metric').textContent=state.mode==='repair'?(state.tested?`第一品絲弦隙 ${state.gap.toFixed(3)} mm`:'壓第三格，測量第一品絲弦隙'):'聽聽看琴主的吉他';$('safe-zone').style.left=((a+.08)/.44*100)+'%';$('safe-zone').style.width=((b-a)/.44*100)+'%';$('marker').style.left=((state.gap+.08)/.44*100)+'%';$('marker').style.visibility=state.tested?'visible':'hidden';$('file').classList.toggle('holding',state.filing);$('powder').classList.toggle('holding',state.powder);}
function endFile(){state.filing=false;dragId=null;sound.grind(false);$('file').classList.remove('holding');}
function tune(){let pool=Array.from({length:7},(_,i)=>i).filter(i=>!state.usedTunes.includes(i));let n=pool[Math.floor(Math.random()*pool.length)];state.usedTunes.push(n);return n;}
async function audition(kind=quality(),music=true){sound.stop();const epoch=state.epoch;try{const duration=await sound.voice(customer.userData.female,kind);if(epoch!==state.epoch)return;if(music)sound.music((state.stage*2+state.kind)%7,kind,duration+.25);}catch(e){say('語音載入中斷，點「再聽一次」重新載入。');sound.ready=null;console.error(e);}}
function newCustomer(){state.epoch++;state.kind=Math.floor(Math.random()*6);state.type=Math.floor(Math.random()*5);state.mood=Math.random();state.gap=Math.random()<.5?.23+Math.random()*.09:-.02-Math.random()*.045;state.tested=false;state.powder=false;state.mode='customer';scene.remove(customer);customer=person(state.kind,state.type);customer.position.set(1.65,0,.7);scene.add(customer);controls('customer');say(quality()==='high'?'好難按喔，上弦枕是不是太高了？':'好像太低了，聲音有雜音。');$('instruction').textContent='點右側「修理」，把吉他放上工作檯。';refresh();audition();}
async function start(){if($('start').disabled)return;$('start').disabled=true;$('start').textContent='準備音樂與客人語音…';try{await sound.preload();state.stage=0;state.total=0;state.ledger=[];state.usedTunes=[];state.started=performance.now();state.tests=0;state.reworks=0;hide('menu',true);hide('end',true);newCustomer();}catch(e){say('音訊未載入，請再按一次開始。');$('best').textContent='語音載入失敗，請確認網路後重試。';sound.ready=null;console.error(e);}finally{$('start').disabled=false;$('start').textContent='開始接單 →';}}
function repair(){state.epoch++;sound.stop();endFile();const held=customer.userData.held;flyingGuitar=held.clone();held.getWorldPosition(flyingGuitar.position);held.getWorldQuaternion(flyingGuitar.quaternion);flyingGuitar.visible=true;scene.add(flyingGuitar);transition=performance.now();state.mode='repair';state.tested=false;controls('repair');neck.visible=false;$('instruction').textContent='按住磨會慢慢降槽；磨低了可加骨粉，再加快乾膠。';say('完整弦線經過上弦枕。橘色虛線是中間看不到的溝槽。');refresh();}
function test(){if(state.mode!=='repair')return;endFile();state.tested=true;state.tests++;const q=quality();say(q==='good'?'一點小縫隙，沒碰到第一品絲，手感剛剛好！':q==='high'?'第一品絲上方縫隙太大，還要再磨低一點。':'弦太低了！請先加骨粉，再點快乾膠補槽。');$('instruction').textContent='手指壓第三格，弦向下變斜。青色短線標出第一品絲弦隙。';refresh();}
function powder(){if(state.mode!=='repair')return;endFile();state.powder=true;state.tested=false;say('骨粉放進溝槽了，接著點「加快乾膠」固定。');refresh();}
function glue(){if(state.mode!=='repair')return;endFile();if(!state.powder){say('請先加骨粉，快乾膠才能把溝槽填起來。');return;}state.powder=false;state.tested=false;state.gap=.275;state.reworks++;say('溝槽補高了！現在可以重新慢慢磨。');refresh();}
function burst(){sound.pop();for(let i=0;i<28;i++){const p=ball(scene,.045,['#d99073','#e9c96b','#82aaa0','#b29aba'][i%4],.5,3.3,.2);p.userData={velocity:new T.Vector3((Math.random()-.5)*3,Math.random()*2+1,(Math.random()-.5)*2),life:1.6};fireworks.push(p);}}
async function deliver(){if(state.mode!=='repair')return;endFile();if(state.powder){say('骨粉還沒固定，請先加快乾膠。');return;}state.epoch++;const q=quality();state.mode=q==='good'?'celebrate':'failed';controls('result');$('retry').hidden=q==='good';$('next').hidden=q!=='good';$('next').disabled=true;refresh();if(q!=='good'){say(q==='high'?'客人：好難按喔，還是太高了！':'客人：好像太低了，聲音有雜音！');$('instruction').textContent='客人沒有收下，繼續修理這把吉他。';audition(q);return;}
const l=levels[state.stage],fee=l.pay[0]+Math.floor(Math.random()*(l.pay[1]-l.pay[0]+1)),tip=state.mood>.5&&Math.random()<.045?Math.round(fee*(.06+Math.random()*.09)):0;state.ledger.push({level:l.name,fee,tip,gap:Number(state.gap.toFixed(3)),customer:customers[state.kind],guitar:types[state.type]});state.total+=fee+tip;celebrationAt=performance.now();burst();say(tip?`修好了！工資 $${fee}，琴主心情好再給 $${tip} 小費！`:`修好了！收到工資 $${fee}。聽聽看漂亮的吉他聲。`);$('instruction').textContent='鏡頭拉遠，琴主試彈中…';refresh();sound.stop();const epoch=state.epoch;let duration=0;try{duration=await sound.voice(customer.userData.female,'good');}catch{sound.ready=null;}if(epoch!==state.epoch)return;const musicTime=sound.music(tune(),'good',duration+.1);setTimeout(()=>{if(epoch===state.epoch){$('next').disabled=false;$('next').textContent=state.stage===2?'完成接單 →':'下一位琴主 →';$('instruction').textContent=state.stage===2?'三張委託都完成了！':'這一單完成，準備迎接下一位琴主。';}},Math.max(1000,musicTime*1000));}
function records(){try{return JSON.parse(localStorage.getItem('qaf-guitar-nut-records-v1')||'[]');}catch{return [];}}
function finish(){state.epoch++;state.mode='final';sound.stop();const elapsed=Math.round((performance.now()-state.started)/1000);const record={total:state.total,time:elapsed,date:new Date().toLocaleDateString('zh-TW'),ledger:state.ledger};let list=[record,...records()].sort((a,b)=>b.total-a.total||a.time-b.time).slice(0,10);let saved=true;try{localStorage.setItem('qaf-guitar-nut-records-v1',JSON.stringify(list));}catch{saved=false;}$('receipt').innerHTML=state.ledger.map(r=>`<p>${r.level}<strong>$${r.fee}${r.tip?' + 小費 $'+r.tip:''}</strong></p>`).join('')+`<p>總收入<strong>$${state.total.toLocaleString()}</strong></p>`;$('record').textContent=`完成時間 ${elapsed} 秒 · 測試 ${state.tests} 次\n${saved?'本機最高收入 $'+list[0].total.toLocaleString():'此瀏覽器無法保存紀錄'}`;hide('end',false);}
function next(){if(state.mode!=='celebrate'||$('next').disabled)return;if(state.stage===2)finish();else{sound.stop();state.stage++;newCustomer();}}
function stopAll(){endFile();state.epoch++;sound.stop();if(state.mode==='celebrate'){$('next').disabled=false;$('instruction').textContent='這一單完成，可以繼續下一張委託。';}}
$('start').onclick=start;$('again').onclick=start;$('repair').onclick=repair;$('retry').onclick=repair;$('test').onclick=test;$('powder').onclick=powder;$('glue').onclick=glue;$('deliver').onclick=deliver;$('next').onclick=next;$('listen').onclick=()=>{sound.unlock();audition();};$('sound').onclick=async()=>{await sound.unlock();$('sound').textContent=sound.toggle()?'音效 ON':'音效 OFF';};
$('file').addEventListener('pointerdown',async e=>{e.preventDefault();if(state.mode!=='repair'||dragId!==null)return;if(state.powder){say('先點快乾膠固定骨粉，再打磨。');return;}dragId=e.pointerId;$('file').setPointerCapture(e.pointerId);state.filing=true;state.tested=false;refresh();await sound.unlock();if(state.filing)sound.grind(true);});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>$('file').addEventListener(ev,endFile));window.addEventListener('blur',endFile);document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAll();if(sound.ctx)sound.ctx.suspend();}});window.addEventListener('pagehide',stopAll);document.querySelectorAll('a').forEach(a=>a.addEventListener('click',stopAll));document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('selectstart',e=>e.preventDefault());document.addEventListener('dragstart',e=>e.preventDefault());
function resize(){const b=$('scene').getBoundingClientRect();renderer.setSize(b.width,b.height);camera.aspect=b.width/b.height;close.z=.6+4.9/(2*Math.tan(T.MathUtils.degToRad(43/2))*camera.aspect);camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('scene'));resize();$('loading').hidden=true;let best=records()[0];if(best)$('best').textContent='這台裝置最高收入 $'+best.total.toLocaleString();
function label(id,p){const b=$('scene').getBoundingClientRect(),a=$('app').getBoundingClientRect(),v=neck.localToWorld(p.clone()).project(camera);$(id).style.left=((v.x*.5+.5)*b.width+b.left-a.left)+'px';$(id).style.top=((-v.y*.5+.5)*b.height+b.top-a.top)+'px';}
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.05);last=now;if(state.filing&&state.mode==='repair'){state.gap=Math.max(-.08,state.gap-dt*.014);refresh();}const near=state.mode==='repair';customer.visible=!near;scene.children.forEach(m=>{if(m.userData.workbench)m.visible=!near;});if(flyingGuitar){flyingGuitar.position.lerp(new T.Vector3(-.2,1.8,.6),1-Math.exp(-dt*5));flyingGuitar.quaternion.slerp(new T.Quaternion().setFromEuler(new T.Euler(-Math.PI/2,0,Math.PI/2)),1-Math.exp(-dt*5));if(now-transition>750){scene.remove(flyingGuitar);flyingGuitar=null;neck.visible=near;}}camera.position.lerp(near?close:wide,1-Math.exp(-dt*4));look.lerp(near?closeTarget:wideTarget,1-Math.exp(-dt*4));camera.lookAt(look);updateInspection(neck,state.gap,state.tested,state.filing,now/1000,state.powder);if(near){label('nut-label',new T.Vector3(0,.95,0));label('fret-label',new T.Vector3(.85,.06,.4));label('third-label',new T.Vector3(2.15,1.05,0));}customer.userData.arm.rotation.z=now<sound.until?Math.sin(now*.022)*.14:Math.sin(now*.0018)*.025;customer.rotation.y=Math.sin(now*.0007)*.025;if(state.mode==='celebrate'&&now-celebrationAt>650&&now-celebrationAt<700){burst();}fireworks=fireworks.filter(p=>{p.userData.life-=dt;p.userData.velocity.y-=dt*2;p.position.addScaledVector(p.userData.velocity,dt);p.scale.setScalar(Math.max(0,p.userData.life));if(p.userData.life<=0){scene.remove(p);p.geometry.dispose();p.material.dispose();return false;}return true;});renderer.render(scene,camera);}
requestAnimationFrame(loop);refresh();window.nutGame={state,sound,levels,scene,camera,neck,test,powder,glue,repair,deliver,next,setGap(v){state.gap=v;refresh();},setCustomer(kind,type){scene.remove(customer);customer=person(kind,type);customer.position.set(1.65,0,.7);scene.add(customer);state.kind=kind;state.type=type;refresh();},skipCelebration(){ $('next').disabled=false;next();},sampleMusic(i){sound.stop();sound.music(i);}};
