// Real recorded guitar and drum voices; original game arrangements. See credits.html.
const BASE='../ankle-breaker/samples/';
const grid=notes=>notes.flatMap(note=>[note,null]);
// 32 slots per bar. Stages 1/2: independent riffs and 32nd-note shred solos. Stage 3 kept as approved.
export const STYLES=[
{"name": "ROAD METAL", "bpm": 160, "key": "E minor / chromatic tension", "root": 0, "accent": [0, 8, 16, 24], "gate": 2.2, "reference": "https://youtu.be/wupHhdlF27Q?t=126", "phrases": [[0, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, -2, null, -2, null, 1, null, 0, null, 0, null, 0, 0, 1, null, 0, null], [0, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, -6, null, -6, null, -2, null, 1, null, 0, null, 0, 0, 0, null, null, null], [0, null, 0, 0, 0, null, 0, 0, 3, null, 2, null, 0, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 6, null, 5, null, 3, null, 2, null], [0, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 1, null, 0, null, 7, null, 5, null, 3, null, 2, null, 0, null, 0, 0, 0, null, null, null]], "lead": [[71, 74, 78, 74, 71, 74, 78, 74, 72, 75, 79, 75, 72, 75, 79, 75, 74, 78, 81, 78, 74, 78, 81, 78, 76, 79, 83, 79, 78, 76, 74, 71], [78, 81, 83, 81, 78, 81, 83, 81, 79, 83, 86, 83, 79, 83, 86, 83, 81, 84, 88, 84, 81, 84, 88, 84, 86, 83, 81, 79, 78, 79, 81, 83], [83, 86, 88, 86, 83, 86, 88, 86, 84, 86, 88, 86, 84, 86, 88, 86, 86, 88, 90, 88, 86, 88, 90, 88, 88, 86, 84, 83, 81, 83, 86, 88]], "leadStride": 1, "voice": "gallop-palm", "openSlots": [16, 18, 20, 22], "openLength": 0.16},{"name": "PERCUSSIVE GROOVE", "bpm": 184, "key": "Low B / chromatic tension", "root": -5, "accent": [0, 6, 10, 16, 20, 24], "gate": 1.8, "reference": "https://youtu.be/qqK1FrO3BdM?t=155", "phrases": [[0, null, null, null, null, null, 0, null, null, null, 0, null, 0, null, null, null, -1, null, null, null, -3, null, null, null, 0, null, 0, null, null, null, null, null], [0, null, null, null, 0, null, null, null, null, null, null, null, -1, null, 0, null, null, null, null, null, -4, null, null, null, -3, null, -1, null, -3, null, null, null], [0, null, 0, null, null, null, null, null, 0, null, null, null, null, null, 0, null, -1, null, null, null, null, null, -3, null, 0, null, null, null, 0, null, null, null], [0, null, null, null, null, null, 0, null, null, null, -1, null, 0, null, null, null, -4, null, null, null, -3, null, null, null, -1, null, -3, null, 0, null, null, null]], "lead": [[71, 72, 74, 77, 74, 72, 71, 69, 71, 74, 77, 78, 77, 74, 72, 71, 72, 74, 77, 79, 77, 74, 72, 71, 77, 74, 72, 71, 69, 71, 72, 77], [77, 78, 81, 84, 81, 78, 77, 74, 77, 81, 84, 85, 84, 81, 78, 77, 78, 81, 84, 86, 84, 81, 78, 77, 84, 81, 78, 77, 74, 77, 78, 84], [83, 84, 87, 90, 87, 84, 83, 81, 83, 87, 90, 91, 90, 87, 84, 83, 84, 87, 90, 93, 90, 87, 84, 83, 91, 90, 87, 84, 83, 87, 90, 90]], "leadStride": 1, "voice": "stop-start-low-b", "openSlots": [0, 16, 20, 24], "openLength": 0.14},
 {name:'EXTREME THRASH',bpm:212,key:'E / semitone neighbour riffs',root:0,accent:[0,8,16,24],gate:2.0,reference:'https://youtu.be/5rJ-awAHA4k?t=235',phrases:[
  grid([12,13,12,null,0,0,0,0,0,0,11,12,11,0,0,null]),
  grid([11,12,11,0,10,11,10,0,9,10,9,0,0,0,0,null]),
  grid([0,0,12,13,12,0,0,0,14,13,12,11,10,9,0,null]),
  grid([11,12,11,0,9,10,9,0,8,9,8,0,7,6,1,null])
 ],lead:[[71, 72, 71, 74, 67, 66, 67, 71, 72, 71, 74, 73, 72, 71, 67, 69, 76, 77, 76, 79, 72, 71, 72, 76, 77, 76, 79, 78, 77, 76, 72, 76], [76, 77, 76, 79, 72, 71, 72, 76, 79, 78, 77, 76, 72, 71, 76, 79, 81, 82, 81, 84, 77, 76, 77, 81, 84, 83, 82, 81, 77, 76, 81, 84], [83, 84, 83, 86, 79, 78, 79, 83, 86, 85, 84, 83, 79, 78, 83, 86, 88, 89, 88, 91, 84, 83, 84, 88, 91, 90, 89, 88, 84, 86, 88, 91]],leadStride:1,voice:'approved-thrash-shred'}
];
// One kit, one groove. Fills replace hats/backbeat; no duplicate cymbals or layered blast pattern.
export function drumScore(stage,bar,n,pitch,solo=false){
 const hits=[],fill=bar%4===3&&n>=24,attack=pitch!==null,hit=(name,gain)=>hits.push({name,gain});
 if(fill){
  if(n%2===0)hit(['snare','tom-high','tom-mid','tom-low'][(n-24)/2],.57);
  if(n===24&&attack)hit('kick',.62);
  return hits;
 }
 const backbeat=stage===1?n===16:n===8||n===24;
 if(backbeat)hit('snare',.65);
 if(n%4===0){if(n===0&&bar%2===0)hit('crash',.18);else hit('hh',n%8===0?.24:.18);}
 // Follow rhythm-guitar attacks and rests, never the dense solo clock.
 if(attack&&(stage===1||n%8===0||[3,6,11,14,19,22,27,30].includes(n)||stage===2&&[2,10,18,26].includes(n)))hit('kick',n%8===0?.68:.54);
 return hits;
}
export class Sound{
 constructor(){this.enabled=true;this.nodes=new Set();this.buffers={};this.events=[];this.serial=0;this.clock=null;this.config=[];this.mode='off';this.trim={};}
 async unlock(){if(!this.ctx){const c=this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=c.createGain();this.master.gain.value=.63;const hp=c.createBiquadFilter();hp.type='highpass';hp.frequency.value=65;const lp=c.createBiquadFilter();lp.type='lowpass';lp.frequency.value=6700;const comp=c.createDynamicsCompressor();comp.threshold.value=-12;comp.knee.value=8;comp.ratio.value=3;comp.attack.value=.006;comp.release.value=.13;this.analyser=c.createAnalyser();this.analyser.fftSize=1024;this.master.connect(hp).connect(lp).connect(comp).connect(this.analyser).connect(c.destination);this.guitar=c.createGain();this.drums=c.createGain();this.drums.gain.value=.66;this.drums.connect(this.master);this.lead=c.createGain();this.lead.gain.value=.42;const leadHP=c.createBiquadFilter(),leadLP=c.createBiquadFilter(),leadComp=c.createDynamicsCompressor();leadHP.type='highpass';leadHP.frequency.value=380;leadLP.type='lowpass';leadLP.frequency.value=4300;leadComp.threshold.value=-22;leadComp.ratio.value=3;leadComp.attack.value=.008;leadComp.release.value=.09;this.lead.connect(leadHP).connect(leadLP).connect(leadComp).connect(this.master);const b=c.createBuffer(1,1,c.sampleRate),s=c.createBufferSource();s.buffer=b;s.connect(this.master);s.start();}await this.ctx.resume();}
 async preload(){await this.unlock();if(!this.ready)this.ready=Promise.all(['low-e-down','low-e-up','kick','snare','hh','crash','tom-high','tom-mid','tom-low'].map(async n=>{const r=await fetch(new URL(BASE+n+'.wav?v=rock-8',import.meta.url));if(!r.ok)throw Error('Missing recording '+n);this.buffers[n]=await this.ctx.decodeAudioData(await r.arrayBuffer());}));await this.ready;if(!this.buffers['sustain']){const r=await fetch(new URL('./samples/sustain.wav?v=rock-8',import.meta.url));if(!r.ok)throw Error('Missing sustained guitar recording');this.buffers.sustain=await this.ctx.decodeAudioData(await r.arrayBuffer());}for(const name of ['lead-g5','open-e2']){if(!this.buffers[name]){const r=await fetch(new URL('./samples/'+name+'.wav?v=rock-8',import.meta.url));if(!r.ok)throw Error('Missing recording '+name);this.buffers[name]=await this.ctx.decodeAudioData(await r.arrayBuffer());}}this.calibrate();this.route(this.config);}
 calibrate(){for(const [name,buffer] of Object.entries(this.buffers)){const data=buffer.getChannelData(0),end=Math.min(data.length,Math.round(buffer.sampleRate*.14));let square=0,peak=0;for(let i=0;i<end;i++){square+=data[i]*data[i];peak=Math.max(peak,Math.abs(data[i]));}const rms=Math.sqrt(square/Math.max(1,end)),target=['low-e-down','low-e-up','sustain','open-e2'].includes(name)?.20:name==='lead-g5'?.16:['hh','crash'].includes(name)?.09:.19;this.trim[name]=Math.min(1.6,target/Math.max(.001,rms),.8/Math.max(.001,peak));}}
 route(config){this.config=config.map(p=>({...p}));if(!this.ctx)return;this.guitar.disconnect();if(this.fxLFO){try{this.fxLFO.stop();}catch{}this.nodes.delete(this.fxLFO);this.fxLFO=null;}if(this.fx){for(const n of this.fx)try{n.disconnect();}catch{}}this.fx=[];const c=this.ctx;let head=this.guitar;const link=n=>{head.connect(n);this.fx.push(n);head=n;};for(const p of config){if(!p.on)continue;const a=p.amount/100,dirty=['fuzz','muff','dirtyrat'].includes(p.id),level=['metalarea','dirtyrat'].includes(p.id)?3:['distortion','muff'].includes(p.id)?2:1;
  if(['drive','distortion','metalarea','fuzz','muff','dirtyrat'].includes(p.id)){const pre=c.createGain(),shape=c.createWaveShaper(),tone=c.createBiquadFilter(),post=c.createGain();pre.gain.value=dirty?1.4+a*(3+level*2):.6+a*(1.5+level*1.2);const curve=new Float32Array(2048),k=dirty?4+a*(5+level*3):1.3+a*(2+level*1.5);for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=Math.tanh(x*k)/Math.tanh(k);}shape.curve=curve;shape.oversample='2x';tone.type='lowpass';tone.frequency.value=dirty?2800+a*1200:3900+a*1000;post.gain.value=dirty?.52:.60;link(pre);link(shape);link(tone);link(post);}
  if(p.id==='echo'){const input=c.createGain(),output=c.createGain(),delay=c.createDelay(1),feedback=c.createGain(),wet=c.createGain(),tone=c.createBiquadFilter();delay.delayTime.value=60/158*.75;feedback.gain.value=.15+a*.42;wet.gain.value=.04+a*.42;tone.type='lowpass';tone.frequency.value=2900;head.connect(input);input.connect(output);input.connect(delay);delay.connect(tone);tone.connect(wet).connect(output);tone.connect(feedback).connect(delay);this.fx.push(input,output,delay,feedback,wet,tone);head=output;}
  if(p.id==='space'){const input=c.createGain(),out=c.createGain(),verb=c.createConvolver(),wet=c.createGain(),hp=c.createBiquadFilter();const duration=.30+a*1.1,ir=c.createBuffer(2,Math.floor(c.sampleRate*duration),c.sampleRate);for(let ch=0;ch<2;ch++){const d=ir.getChannelData(ch);let prior=0;for(let i=0;i<d.length;i++){prior=prior*.6+(Math.random()*2-1)*.4;d[i]=prior*Math.pow(1-i/d.length,2.8);}}verb.buffer=ir;wet.gain.value=.05+a*.3;hp.type='highpass';hp.frequency.value=260;head.connect(input);input.connect(out);input.connect(verb).connect(hp).connect(wet).connect(out);this.fx.push(input,out,verb,wet,hp);head=out;}
  if(p.id==='eq'){const low=c.createBiquadFilter(),mid=c.createBiquadFilter();low.type='lowshelf';low.frequency.value=170;low.gain.value=a*5;mid.type='peaking';mid.frequency.value=850;mid.Q.value=.8;mid.gain.value=-2-a*4;link(low);link(mid);}
  if(['comp','midboost','bomboost'].includes(p.id)){const comp=c.createDynamicsCompressor(),g=c.createGain();comp.threshold.value=-10-a*18;comp.ratio.value=2+a*6;comp.attack.value=.012;comp.release.value=.12;g.gain.value=1.1+a*(p.id==='bomboost'?.65:.3);link(comp);if(p.id!=='comp'){const mid=c.createBiquadFilter();mid.type='peaking';mid.frequency.value=p.id==='midboost'?1100:600;mid.Q.value=.65;mid.gain.value=2+a*5;link(mid);}link(g);}}
 for(const p of config){if(!p.on)continue;const a=p.amount/100;if(p.id==='wah'){const filter=c.createBiquadFilter(),lfo=c.createOscillator(),depth=c.createGain();filter.type='bandpass';filter.frequency.value=1600;filter.Q.value=.6;lfo.frequency.value=1.8+a*3;depth.gain.value=1100;lfo.connect(depth).connect(filter.frequency);link(filter);lfo.start();this.nodes.add(lfo);this.fx.push(depth);this.fxLFO=lfo;}if(p.id==='feedback'){const d=c.createDelay(.8),g=c.createGain(),f=c.createBiquadFilter(),out=c.createGain();d.delayTime.value=.19;g.gain.value=.12+a*.42;f.type='lowpass';f.frequency.value=2600;head.connect(out);head.connect(d).connect(f).connect(g).connect(out);g.connect(d);this.fx.push(d,g,f,out);head=out;}}if(this.stage>0){const bite=c.createBiquadFilter();bite.type='peaking';bite.frequency.value=this.stage===2?1800:850;bite.Q.value=.8;bite.gain.value=this.stage===2?1.3:-2.5;link(bite);}const balance=c.createDynamicsCompressor(),out=c.createGain();balance.threshold.value=-25;balance.knee.value=8;balance.ratio.value=6;balance.attack.value=.003;balance.release.value=.06;out.gain.value=.42;link(balance);link(out);head.connect(this.master);}
 play(name,t,gain=1,semitones=0,duration=null,bass=false){if(!this.enabled||!this.buffers[name])return;gain*=this.trim[name]??1;const c=this.ctx,s=c.createBufferSource(),g=c.createGain();s.buffer=this.buffers[name];s.playbackRate.value=2**(semitones/12);g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(gain,t+.002);if(duration){g.gain.setValueAtTime(gain,t+duration*.62);g.gain.exponentialRampToValueAtTime(.001,t+duration);}if(name==='lead-g5'){s.detune.setValueAtTime(-8,t);s.detune.linearRampToValueAtTime(0,t+.007);if(duration>.2){s.detune.setValueAtTime(0,t+duration*.4);s.detune.linearRampToValueAtTime(130,t+duration*.75);s.detune.linearRampToValueAtTime(75,t+duration);}}s.connect(g);if(bass){const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=320;g.connect(filter).connect(this.master);s.onended=()=>{this.nodes.delete(s);filter.disconnect();g.disconnect();};}else{g.connect(name==='lead-g5'?this.lead:name.startsWith('low-e')||['sustain','lead-g5','open-e2'].includes(name)?this.guitar:this.drums);s.onended=()=>{this.nodes.delete(s);g.disconnect();};}this.nodes.add(s);s.start(t);if(duration)s.stop(t+duration+.02);this.events.push({name,t,semitones,gain});if(this.events.length>250)this.events.shift();}
 sequence({kind='show',variation=0,stage=0,onNote=()=>{},onFinish=()=>{}}={}){this.stop();if(!this.ctx)return;this.stage=stage;this.route(this.config);const profile=STYLES[stage];const token=this.serial,c=this.ctx,bpm=profile.bpm,step=7.5/bpm,count=kind==='show'?[128,160,192][stage]:kind==='preview'?64:128,quiet=kind==='ambient'?.22:1;this.mode=kind;this.guitar.gain.value=quiet*.67;this.drums.gain.value=quiet*.62*(kind==='show'?1.10:1);this.lead.gain.value=quiet*.75;let next=0,from=c.currentTime+.07,emitted=0;const notes=[];this.lastSequence={kind,stage,bpm,soloNotes:0,riffNotes:0,style:profile.name,reference:profile.reference,key:profile.key,duration:count*step+.15,soloStarts:32*step,soloRate:bpm/(profile.leadStride===1?7.5:15),leadSubdivision:profile.leadStride===1?32:16,drumGain:this.drums.gain.value,voice:profile.voice||'approved-thrash'};
 const soloRuns=profile.lead;
 const pump=()=>{if(token!==this.serial||document.hidden)return;const now=c.currentTime;while(next<count&&from+next*step<now+.18){const index=next++,t=from+index*step,bar=Math.floor(index/32),n=index%32,slot=Math.floor(n/2),solo=kind==='show'&&bar>=1,is16=n%2===0,phrase=profile.phrases[(variation+bar)%profile.phrases.length],pitch=phrase[n],guitar=kind!=='ambient',accent=profile.accent.includes(n);
 if(guitar&&pitch!==null){const open=profile.openSlots?.includes(n)&&pitch!==null;this.play(open?'open-e2':index%4===0?'low-e-down':'low-e-up',t,solo?(accent?.61:.54):accent?.69:.60,pitch+profile.root,open?profile.openLength:Math.min(.12,step*profile.gate));if(n%8===0)this.play('sustain',t,.18,pitch+profile.root-12,.26,true);if(this.config.some(p=>p.on&&p.id==='octave'))this.play('low-e-down',t,.18,pitch+profile.root-12,.18);notes.push({t,index,pitch:pitch+profile.root,accent,solo:false});this.lastSequence.riffNotes++;}
 if(guitar&&solo&&(profile.leadStride===1||is16)){const soloProgress=Math.max(0,Math.min(1,(index-32)/(count-33))),band=Math.min(2,Math.floor(soloProgress*3)),run=soloRuns[band],midi=run[Math.floor((index-32)/(profile.leadStride||2))%run.length];if(midi!==null){if(this.lastSequence.firstSoloMidi===undefined)this.lastSequence.firstSoloMidi=midi;this.lastSequence.lastSoloMidi=midi;this.lastSequence.soloPosition=soloProgress;this.play('lead-g5',t,.47,midi-79,step*(profile.leadStride===1?1.35:2.0));notes.push({t,index,pitch:midi,accent,solo:true,soloProgress});this.lastSequence.soloNotes++;}}

 for(const hit of drumScore(stage,bar,n,pitch,solo))this.play(hit.name,t,hit.gain);}

 while(emitted<notes.length&&notes[emitted].t<=now){onNote({...notes[emitted++],kind});}if(next===count&&now>from+count*step+.12){clearInterval(this.clock);this.clock=null;this.mode='off';onFinish();return;}};this.clock=setInterval(pump,20);pump();return count*step+.22;}
 boom(stage=0){if(!this.enabled||!this.ctx)return;const c=this.ctx,t=c.currentTime,strength=.9+stage*.16;this.lastBoom={hits:1,duration:1.8,stage};const layers=[{length:.38,cutoff:2400,gain:.54,decay:.075},{length:1.8,cutoff:440,gain:1.1,decay:.48},{length:1.3,cutoff:1300,gain:.22,decay:.35}];for(const layer of layers){const buffer=c.createBuffer(1,Math.ceil(c.sampleRate*layer.length),c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const age=i/c.sampleRate,roll=.72+Math.sin(age*31)*.12+Math.sin(age*57)*.1;data[i]=(Math.random()*2-1)*Math.exp(-age/layer.decay)*roll;}const source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=layer.cutoff;gain.gain.value=layer.gain*strength;source.connect(filter).connect(gain).connect(this.master);this.nodes.add(source);source.onended=()=>{this.nodes.delete(source);filter.disconnect();gain.disconnect();};source.start(t);}const body=c.createOscillator(),env=c.createGain();body.type='sine';body.frequency.setValueAtTime(118,t);body.frequency.exponentialRampToValueAtTime(48,t+.65);env.gain.setValueAtTime(.0001,t);env.gain.linearRampToValueAtTime(strength*.6,t+.012);env.gain.exponentialRampToValueAtTime(.001,t+1.2);body.connect(env).connect(this.master);this.nodes.add(body);body.onended=()=>{this.nodes.delete(body);env.disconnect();};body.start(t);body.stop(t+1.25);}
 impact(strength=1){if(!this.enabled||!this.ctx)return;const c=this.ctx,t=c.currentTime,b=c.createBuffer(1,c.sampleRate*.3,c.sampleRate),data=b.getChannelData(0);let z=0;for(let i=0;i<data.length;i++){z=z*.82+(Math.random()*2-1)*.18;data[i]=z*Math.exp(-i/(c.sampleRate*.065));}const s=c.createBufferSource(),g=c.createGain();s.buffer=b;g.gain.value=.3*strength;s.connect(g).connect(this.master);this.nodes.add(s);s.onended=()=>{this.nodes.delete(s);g.disconnect();};s.start(t);}
 stop(){this.serial++;clearInterval(this.clock);this.clock=null;for(const n of this.nodes)try{n.stop();}catch{}this.nodes.clear();if(this.guitar){this.guitar.disconnect();for(const n of this.fx||[])try{n.disconnect();}catch{}this.fx=[];}this.mode='off';}
 level(){if(!this.analyser)return 0;const d=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(d);return Math.sqrt(d.reduce((s,v)=>s+v*v,0)/d.length);}
 dispose(){this.stop();this.ctx?.close();}
}
