// Real recorded guitar and drum voices; composition and DSP are original. See credits.html.
const BASE='../ankle-breaker/samples/';
const phrases=[
 [0,0,null,0,3,null,0,0,5,null,0,0,6,5,3,null],
 [0,null,0,0,0,3,0,null,5,5,null,3,0,0,0,null],
 [0,0,0,null,7,null,6,5,0,null,0,0,3,null,5,null],
 [0,null,0,3,0,null,6,5,0,0,null,0,3,5,6,7]
];
export class Sound{
 constructor(){this.enabled=true;this.nodes=new Set();this.buffers={};this.events=[];this.serial=0;this.clock=null;this.config=[];this.mode='off';}
 async unlock(){if(!this.ctx){const c=this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=c.createGain();this.master.gain.value=.63;const hp=c.createBiquadFilter();hp.type='highpass';hp.frequency.value=65;const lp=c.createBiquadFilter();lp.type='lowpass';lp.frequency.value=6700;const comp=c.createDynamicsCompressor();comp.threshold.value=-16;comp.knee.value=10;comp.ratio.value=4;comp.attack.value=.006;comp.release.value=.13;this.analyser=c.createAnalyser();this.analyser.fftSize=1024;this.master.connect(hp).connect(lp).connect(comp).connect(this.analyser).connect(c.destination);this.guitar=c.createGain();this.drums=c.createGain();this.drums.gain.value=.66;this.drums.connect(this.master);const b=c.createBuffer(1,1,c.sampleRate),s=c.createBufferSource();s.buffer=b;s.connect(this.master);s.start();}await this.ctx.resume();}
 async preload(){await this.unlock();if(!this.ready)this.ready=Promise.all(['low-e-down','low-e-up','kick','snare','hh','crash','tom-high','tom-mid','tom-low'].map(async n=>{const r=await fetch(new URL(BASE+n+'.wav?v=rock-1',import.meta.url));if(!r.ok)throw Error('Missing recording '+n);this.buffers[n]=await this.ctx.decodeAudioData(await r.arrayBuffer());}));await this.ready;if(!this.buffers['sustain']){const r=await fetch(new URL('./samples/sustain.wav?v=rock-1',import.meta.url));if(!r.ok)throw Error('Missing sustained guitar recording');this.buffers.sustain=await this.ctx.decodeAudioData(await r.arrayBuffer());}this.route(this.config);}
 route(config){this.config=config.map(p=>({...p}));if(!this.ctx)return;this.guitar.disconnect();if(this.fx){for(const n of this.fx)try{n.disconnect();}catch{}}this.fx=[];const c=this.ctx;let head=this.guitar;const link=n=>{head.connect(n);this.fx.push(n);head=n;};for(const p of config){if(!p.on)continue;const a=p.amount/100;
  if(p.id==='drive'||p.id==='fuzz'){const pre=c.createGain(),shape=c.createWaveShaper(),tone=c.createBiquadFilter(),post=c.createGain();pre.gain.value=p.id==='fuzz'?1.4+a*4:.6+a*2.5;const curve=new Float32Array(2048),k=p.id==='fuzz'?4+a*7:1.3+a*3;for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=Math.tanh(x*k)/Math.tanh(k);}shape.curve=curve;shape.oversample='2x';tone.type='lowpass';tone.frequency.value=p.id==='fuzz'?3100+a*1200:4200+a*1000;post.gain.value=.61;link(pre);link(shape);link(tone);link(post);}
  if(p.id==='echo'){const input=c.createGain(),output=c.createGain(),delay=c.createDelay(1),feedback=c.createGain(),wet=c.createGain(),tone=c.createBiquadFilter();delay.delayTime.value=60/158*.75;feedback.gain.value=.15+a*.42;wet.gain.value=.04+a*.42;tone.type='lowpass';tone.frequency.value=2900;head.connect(input);input.connect(output);input.connect(delay);delay.connect(tone);tone.connect(wet).connect(output);tone.connect(feedback).connect(delay);this.fx.push(input,output,delay,feedback,wet,tone);head=output;}
  if(p.id==='space'){const input=c.createGain(),out=c.createGain(),verb=c.createConvolver(),wet=c.createGain(),hp=c.createBiquadFilter();const duration=.30+a*1.1,ir=c.createBuffer(2,Math.floor(c.sampleRate*duration),c.sampleRate);for(let ch=0;ch<2;ch++){const d=ir.getChannelData(ch);let prior=0;for(let i=0;i<d.length;i++){prior=prior*.6+(Math.random()*2-1)*.4;d[i]=prior*Math.pow(1-i/d.length,2.8);}}verb.buffer=ir;wet.gain.value=.05+a*.3;hp.type='highpass';hp.frequency.value=260;head.connect(input);input.connect(out);input.connect(verb).connect(hp).connect(wet).connect(out);this.fx.push(input,out,verb,wet,hp);head=out;}
  if(p.id==='eq'){const low=c.createBiquadFilter(),mid=c.createBiquadFilter();low.type='lowshelf';low.frequency.value=170;low.gain.value=a*5;mid.type='peaking';mid.frequency.value=850;mid.Q.value=.8;mid.gain.value=-2-a*4;link(low);link(mid);}
  if(p.id==='comp'){const comp=c.createDynamicsCompressor(),g=c.createGain();comp.threshold.value=-10-a*18;comp.ratio.value=2+a*6;comp.attack.value=.012;comp.release.value=.12;g.gain.value=1.1+a*.3;link(comp);link(g);}}
 head.connect(this.master);}
 play(name,t,gain=1,semitones=0,duration=null,bass=false){if(!this.enabled||!this.buffers[name])return;const c=this.ctx,s=c.createBufferSource(),g=c.createGain();s.buffer=this.buffers[name];s.playbackRate.value=2**(semitones/12);g.gain.setValueAtTime(gain,t);if(duration){g.gain.setValueAtTime(gain,t+duration*.6);g.gain.exponentialRampToValueAtTime(.001,t+duration);}s.connect(g);if(bass){const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=320;g.connect(filter).connect(this.master);s.onended=()=>{this.nodes.delete(s);filter.disconnect();g.disconnect();};}else{g.connect(name.startsWith('low-e')||name==='sustain'?this.guitar:this.drums);s.onended=()=>{this.nodes.delete(s);g.disconnect();};}this.nodes.add(s);s.start(t);if(duration)s.stop(t+duration+.02);this.events.push({name,t,semitones,gain});if(this.events.length>250)this.events.shift();}
 sequence({kind='show',variation=0,onNote=()=>{},onFinish=()=>{}}={}){this.stop();if(!this.ctx)return;const token=this.serial,c=this.ctx,step=15/158,count=kind==='show'?96:kind==='preview'?32:64,quiet=kind==='ambient'?.15:1;this.mode=kind;this.guitar.gain.value=quiet*.8;this.drums.gain.value=quiet*.63;let next=0,from=c.currentTime+.06,emitted=0;const notes=[];
 const pump=()=>{if(token!==this.serial||document.hidden)return;const now=c.currentTime;while(next<count&&from+next*step<now+.18){const index=next++,t=from+index*step,bar=Math.floor(index/16),n=index%16,phrase=phrases[(variation+bar)%phrases.length],pitch=phrase[n];if(pitch!==null){const accent=n%4===0,gain=accent?.68:.48;const name=n===14&&bar%2===1?'sustain':index%2?'low-e-up':'low-e-down';this.play(name,t,gain,pitch,name==='sustain'?.27:null);if(n%4===0)this.play('sustain',t,.22,pitch-12,.32,true);notes.push({t,index,pitch,accent});}this.play('hh',t,n%2?.25:.38);if(n===4||n===12)this.play('snare',t,.88);if(n%4===0||n===3||n===10||bar%2===1&&n===7)this.play('kick',t,.84);if(n===0&&bar%2===0)this.play('crash',t,.39);if(bar%4===3&&n>=12){this.play(['tom-high','tom-mid','tom-low','snare'][n-12],t,.76);}}
 while(emitted<notes.length&&notes[emitted].t<=now){const note=notes[emitted++];onNote({...note,kind});}if(next===count&&now>from+count*step+.38){clearInterval(this.clock);this.clock=null;this.mode='off';onFinish();return;}};this.clock=setInterval(pump,25);pump();return count*step+.5;}
 impact(strength=1){if(!this.enabled||!this.ctx)return;const c=this.ctx,t=c.currentTime,b=c.createBuffer(1,c.sampleRate*.3,c.sampleRate),data=b.getChannelData(0);let z=0;for(let i=0;i<data.length;i++){z=z*.82+(Math.random()*2-1)*.18;data[i]=z*Math.exp(-i/(c.sampleRate*.065));}const s=c.createBufferSource(),g=c.createGain();s.buffer=b;g.gain.value=.3*strength;s.connect(g).connect(this.master);this.nodes.add(s);s.onended=()=>{this.nodes.delete(s);g.disconnect();};s.start(t);}
 stop(){this.serial++;clearInterval(this.clock);this.clock=null;for(const n of this.nodes)try{n.stop();}catch{}this.nodes.clear();if(this.guitar){this.route(this.config);}this.mode='off';}
 level(){if(!this.analyser)return 0;const d=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(d);return Math.sqrt(d.reduce((s,v)=>s+v*v,0)/d.length);}
 dispose(){this.stop();this.ctx?.close();}
}
