import {T,build} from './world.js?v=rock-10';
import {Sound,STYLES} from './audio.js?v=rock-10';
import {CATALOG as catalog,LEVELS,calculate} from './rules.js?v=rock-10';
const $=id=>document.getElementById(id),world=build(),sound=new Sound(),renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('scene').append(renderer.domElement);const camera=new T.PerspectiveCamera(44,1,.1,65),target=new T.Vector3(-.15,1.25,.25),cameraBase=new T.Vector3();
let saved={money:0,owned:catalog.filter(p=>p.tier===0).map(p=>p.id),best:0};try{const prior=JSON.parse(localStorage.getItem('qaf-rock-demolition-v2')||localStorage.getItem('qaf-rock-demolition-v1'));if(prior&&Number.isFinite(prior.money)&&prior.money>=0)saved={...saved,money:prior.money,owned:[...new Set([...saved.owned,...(prior.owned||[]).filter(id=>catalog.some(p=>p.id===id))])],best:prior.best||0};}catch{}
const state={mode:'menu',stage:0,damage:0,money:saved.money,owned:new Set(saved.owned),pedals:[null,null,null],variation:0,notes:0,soloNotes:0,totalEarned:0,earnings:0,editing:0,selectedSlot:0,pulse:0,shake:0,tremor:0,started:false,exploded:false,blast:null,energy:0};let last=performance.now(),pendingResult=0,drag=null,hasDragged=false,showStart=0;
function persist(){saved={money:state.money,owned:[...state.owned],best:Math.max(saved.best,state.totalEarned)};try{localStorage.setItem('qaf-rock-demolition-v2',JSON.stringify(saved));}catch{}}
function resize(){const w=$('scene').clientWidth,h=$('scene').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;const narrow=w/h<1.45;cameraBase.set(narrow?5.5:6.8,4.6+state.stage*.7,(narrow?9.2:9.4)+state.stage*2.0);target.y=1.25+state.stage*.8;camera.position.copy(cameraBase);camera.lookAt(target);camera.updateProjectionMatrix();}
function lockHeight(){document.documentElement.style.setProperty('--height',innerHeight+'px');}lockHeight();new ResizeObserver(resize).observe($('scene'));window.addEventListener('orientationchange',()=>setTimeout(()=>{lockHeight();resize();},250));resize();
function pedalDOM(p,i){if(!p)return `<button class="empty-slot ${state.selectedSlot===i?'chosen':''}" data-slot="${i}" aria-label="空格 ${i+1}，選擇此格"><span>＋</span><small>選一顆效果器</small></button>`;const d=catalog.find(c=>c.id===p.id);return `<button class="pedal ${p.on?'':'off'}" data-slot="${i}" style="--paint:${d.color};--turn:${-135+p.amount*2.7}deg" aria-label="調整 ${d.name}，${p.amount}%，${p.on?'開啟':'關閉'}"><i class="screw">⊕</i><i class="screw right">⊕</i><div class="knobs"><i class="knob"></i><i class="knob small"></i></div><span class="knob-label">${d.label} / TONE</span><strong>${d.name}</strong><span class="model">${d.model}</span><i class="led"></i><i class="footswitch"></i><span class="value">${p.on?Math.round(d.energy*p.amount/100):0} ENERGY</span></button>`;}
function updateEnergy(){const c=calculate(state.pedals,state.stage);state.energy=c.energy;$('energy').textContent=c.energy;$('defense').textContent=c.defense;$('energy-ratio').textContent=c.energy?`${c.grade} · 火勢 ${Math.round(Math.min(1,c.fire)*100)}%`:'盤上還沒有能量';$('synergy').textContent=c.bonus?`組合 +${c.bonus}`:'自由組合';$('perform').disabled=state.mode!=='board'||!c.energy;$('audition').disabled=state.mode!=='board'||!c.energy;return c;}
function renderBoard(){ $('money').textContent=state.money.toLocaleString('zh-TW');$('pedals').innerHTML=state.pedals.map(pedalDOM).join('');$('chain-name').textContent=state.pedals.filter(Boolean).map(p=>catalog.find(c=>c.id===p.id).name).join(' → ')||'空盤 · 從下方選一顆';$('rack-count').textContent=`${catalog.filter(p=>p.tier<=state.stage).length} 顆可選`; $('rack').innerHTML=catalog.filter(p=>p.tier<=state.stage).map(p=>`<button class="rack-pedal ${state.owned.has(p.id)?'':'locked'} ${state.pedals.some(e=>e?.id===p.id)?'selected':''}" data-id="${p.id}" style="--paint:${p.color}" aria-label="${state.owned.has(p.id)?'裝上':'購買'} ${p.name}，能量 ${p.energy}${p.cost&&!state.owned.has(p.id)?'，'+p.cost+'元':''}"><i class="mini-pedal"></i><div><strong>${p.name}</strong><small>${p.energy} ⚡${state.owned.has(p.id)?'':' · $'+p.cost}</small></div></button>`).join('');sound.route(state.pedals.filter(Boolean));updateEnergy();persist();}
function edit(i){if(state.mode!=='board')return;state.selectedSlot=i;if(!state.pedals[i]){renderBoard();$('notice').textContent=`已選第 ${i+1} 格，點下方效果器裝上。`;return;}state.editing=i;const p=state.pedals[i],d=catalog.find(c=>c.id===p.id);$('edit-name').textContent=d.name;$('amount-label').textContent=d.label;$('edit-description').textContent=d.description;$('amount').value=p.amount;updateEdit();$('editor').showModal();}
function updateEdit(){const p=state.pedals[state.editing],d=catalog.find(c=>c.id===p.id);$('amount-value').textContent=`${p.amount}% · ${p.on?Math.round(d.energy*p.amount/100):0} ⚡`;$('big-knob').style.transform=`rotate(${-135+p.amount*2.7}deg)`;$('bypass').textContent=p.on?'已開啟 ●':'旁通 ○';$('bypass').style.color=p.on?'#b4d7a3':'#a0a4a9';}
function install(id,slot=state.selectedSlot){if(state.mode!=='board')return;const d=catalog.find(c=>c.id===id);if(!d||d.tier>state.stage)return;if(!state.owned.has(id)){if(state.money<d.cost){$('notice').textContent=`${d.name} 還差 $${d.cost-state.money}。先用已有器材拆除。`;return;}state.money-=d.cost;state.owned.add(id);$('notice').textContent=`${d.name} 入手！${d.energy} 能量。`;}else $('notice').textContent=`${d.name} 裝上第 ${slot+1} 格。`;const existing=state.pedals.findIndex(p=>p?.id===id);if(existing>=0)[state.pedals[existing],state.pedals[slot]]=[state.pedals[slot],state.pedals[existing]];else state.pedals[slot]={id,amount:100,on:true};state.selectedSlot=state.pedals.findIndex(p=>!p);if(state.selectedSlot<0)state.selectedSlot=(slot+1)%3;renderBoard();}
function beginAmbient(){if(state.mode==='board'&&!document.hidden)sound.sequence({kind:'ambient',stage:state.stage,onFinish:beginAmbient});}
function prepareStage(){clearTimeout(pendingResult);pendingResult=0;world.prepareStage(state.stage);Object.assign(state,{mode:'board',damage:0,notes:0,soloNotes:0,earnings:0,pulse:0,shake:0,exploded:false,blast:null});$('end').hidden=true;$('menu').hidden=true;$('riff-caption').hidden=true;$('game').classList.remove('performing');$('damage').innerHTML='0<small>%</small>';$('damage-bar').style.width='0%';$('perform').textContent='開彈拆房子 ↗';document.querySelector('.job span').textContent=`委託 ${state.stage+1} / 3`;document.querySelector('.job strong').textContent=LEVELS[state.stage].name;document.querySelector('.site-tag').innerHTML='<span class="live-dot"></span> 顧客營業中 · 等待拆除';$('notice').textContent=LEVELS[state.stage].unlock;renderBoard();resize();beginAmbient();}
async function start(){if($('start').disabled)return;let loading=true;$('start').disabled=true;$('again').disabled=true;$('load-status').textContent='真實吉他與鼓音色載入中…';try{await sound.preload(({loaded,total})=>{if(!loading)return;$('load-progress').max=total;$('load-progress').value=loaded;$('load-percent').textContent=Math.round(loaded/total*100)+'%';$('load-label').textContent=loaded===total?'音色準備完成':'正在載入音色';$('load-status').textContent=loaded===total?'準備完成，進入拆除現場…':`音色已準備 ${loaded} / ${total}`;});state.stage=0;state.pedals=[null,null,null];state.selectedSlot=0;state.totalEarned=0;prepareStage();window.QAFPlayCount?.start('rock-demolition');state.started=true;}catch(e){loading=false;sound.ready=null;$('load-label').textContent='載入暫停，可重試';$('load-status').textContent='音色載入失敗，請再按一次。';console.error(e);}finally{loading=false;$('start').disabled=false;$('again').disabled=false;}}
function nextStage(){if(state.stage>=2)return start();state.stage++;prepareStage();}
function hit(n){state.pulse=n.accent?1:n.solo?.8:.6;world.note(n.solo,n.soloProgress);if(state.mode!=='show')return;state.notes++;if(n.solo){state.soloNotes++;$('riff-caption').querySelector('strong').textContent=['速彈登場，火勢升級！','Solo 加速，地面開始搖！','終極 Solo，整條街都保不住！'][state.stage];}const c=calculate(state.pedals,state.stage),value=(n.solo?.38:n.accent?1.65:1.00)*Math.max(.14,Math.min(2,c.ratio));state.damage=Math.min(100,state.damage+value*1.9);world.ignite(c.ratio,state.damage);world.damage(Math.min(68,state.damage*.68),.25+c.ratio*.8);state.shake=n.accent?.28+state.stage*.2:.1;/* No extra impact layer over the musical kit. */$('damage').innerHTML=Math.floor(state.damage)+'<small>%</small>';$('damage-bar').style.width=state.damage+'%';document.querySelector('.site-tag').innerHTML=`<span class="live-dot"></span> ${c.grade} · ${Math.round(c.fire*100)}% 火勢`;}
async function perform(){if(state.mode!=='board'||!state.energy)return;await sound.unlock();state.mode='show';showStart=performance.now();state.variation=(state.variation+1)%4;$('game').classList.add('performing');$('perform').disabled=$('audition').disabled=true;$('editor').close();$('riff-caption').hidden=false;$('riff-caption').querySelector('span').textContent=`${LEVELS[state.stage].bpm} BPM / ${['ROAD METAL','GROOVE','FAST THRASH'][state.stage]}`;$('riff-caption').querySelector('strong').textContent='Riff 開始，火勢準備失控。';$('notice').textContent='Riff → 速彈 Solo → 爆破';sound.route(state.pedals.filter(Boolean));sound.sequence({kind:'show',stage:state.stage,variation:state.variation,onNote:hit,onFinish:()=>{if(state.damage>=99.9){detonate();}else{state.mode='board';$('game').classList.remove('performing');$('riff-caption').hidden=true;$('perform').textContent='再來一段！ ↗';$('notice').textContent='還沒拆完。加強能量，或再來一段！';updateEnergy();beginAmbient();}}});}
function detonate(){if(state.mode!=='show')return;state.mode='settling';state.exploded=true;state.blast=world.explode(calculate(state.pedals,state.stage).ratio);sound.stop();sound.boom(state.stage);state.shake=state.stage===0?2.5:4.5;$('damage').innerHTML='100<small>%</small>';document.querySelector('.site-tag').innerHTML='<span class="live-dot"></span> 爆破完成';pendingResult=setTimeout(finish,state.stage===2?2800:2200);}
function finish(){pendingResult=0;if(state.mode!=='settling')return;state.mode='end';const c=calculate(state.pedals,state.stage),fee=LEVELS[state.stage].fee,bonus=Math.round(c.energy*.4/10)*10;state.earnings=fee+bonus;state.totalEarned+=state.earnings;state.money+=state.earnings;persist();$('result-percent').innerHTML='100<small>%</small>';$('fee').textContent='$'+fee;$('bonus').textContent='$'+bonus;$('earned').textContent='$'+state.earnings.toLocaleString('zh-TW');$('end-title').textContent=state.stage===2?'人也飛走了！':'拆得漂亮。';$('end-description').textContent=state.stage===2?'房子、音箱、吉他……全部收工。':state.stage===1?'地震過後，吉他手表示：還好沒事。':'唱片行退場，搖滾留在現場。';$('end-stamp').textContent=`CONTRACT COMPLETE / 00${state.stage+1}`;$('best').textContent=`本輪累計 $${state.totalEarned.toLocaleString('zh-TW')} · 器材基金 $${state.money.toLocaleString('zh-TW')}`;$('again').textContent=state.stage<2?'下一關 · 新器材解鎖 →':'從空盤再拆三關 ↻';$('end').hidden=false;$('game').classList.remove('performing');sound.stop();}
async function audition(){if(state.mode!=='board'||!state.energy)return;await sound.unlock();$('audition').disabled=true;$('notice').textContent='試音中 · 不會破壞房子';sound.route(state.pedals.filter(Boolean));sound.sequence({kind:'preview',stage:state.stage,variation:state.variation,onNote:n=>{state.pulse=n.accent?.8:.5;world.note(n.solo,n.soloProgress);},onFinish:()=>{updateEnergy();$('notice').textContent='準備好了，就開彈。';beginAmbient();}});}
$('start').onclick=start;$('again').onclick=nextStage;$('perform').onclick=perform;$('audition').onclick=audition;$('reorder').onclick=()=>{if(state.mode!=='board')return;state.pedals.push(state.pedals.shift());renderBoard();$('notice').textContent='接線順序已改變。';};$('pedals').addEventListener('click',e=>{const p=e.target.closest('[data-slot]');if(p&&!hasDragged){const i=Number(p.dataset.slot);if(state.pedals[i]&&e.target.closest('.footswitch')){state.pedals[i].on=!state.pedals[i].on;renderBoard();}else edit(i);}});$('rack').addEventListener('click',e=>{const p=e.target.closest('[data-id]');if(p&&!hasDragged)install(p.dataset.id);});$('close-edit').onclick=()=> $('editor').close();$('editor').addEventListener('click',e=>{if(e.target===$('editor'))$('editor').close();});$('amount').oninput=()=>{state.pedals[state.editing].amount=Number($('amount').value);updateEdit();renderBoard();};$('bypass').onclick=()=>{state.pedals[state.editing].on=!state.pedals[state.editing].on;updateEdit();renderBoard();};$('remove-pedal').onclick=()=>{state.pedals[state.editing]=null;state.selectedSlot=state.editing;$('editor').close();renderBoard();};
// Pointer drag is shared by mouse and touch. Tap is retained for small phones.
function dragStart(e){const node=e.target.closest('[data-slot], [data-id]');if(!node||state.mode!=='board')return;hasDragged=false;drag={node,slot:node.dataset.slot!==undefined?Number(node.dataset.slot):null,id:node.dataset.id,x:e.clientX,y:e.clientY,pointer:e.pointerId};node.setPointerCapture(e.pointerId);}
function dragMove(e){if(!drag||drag.pointer!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<9&&!hasDragged)return;hasDragged=true;drag.node.classList.add('dragging');document.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]')?.classList.add('drop-target');}
function dragEnd(e){if(!drag||drag.pointer!==e.pointerId)return;const node=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(hasDragged&&node){const slot=Number(node.dataset.slot);if(drag.id)install(drag.id,slot);else{[state.pedals[drag.slot],state.pedals[slot]]=[state.pedals[slot],state.pedals[drag.slot]];renderBoard();}}drag.node.classList.remove('dragging');document.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));drag=null;setTimeout(()=>hasDragged=false,120);}
for(const id of['pedals','rack']){$(id).addEventListener('pointerdown',dragStart);$(id).addEventListener('pointermove',dragMove);$(id).addEventListener('pointerup',dragEnd);$(id).addEventListener('pointercancel',e=>{if(drag){drag.node.classList.remove('dragging');drag=null;hasDragged=false;}});}
$('sound').onclick=async()=>{await sound.unlock();sound.enabled=!sound.enabled;$('sound').textContent=sound.enabled?'♫ ON':'♫ OFF';sound.master.gain.value=sound.enabled?.63:0;};
function suspend(){sound.stop();clearTimeout(pendingResult);pendingResult=0;if(state.mode==='settling'){finish();}else if(state.mode==='show'){state.mode='board';$('game').classList.remove('performing');$('riff-caption').hidden=true;$('perform').textContent='繼續開彈 ↗';$('notice').textContent='演奏已暫停，按開彈繼續。';updateEnergy();}else if(state.mode==='board')updateEnergy();sound.stop();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();else if(state.mode==='board')beginAmbient();});document.querySelectorAll('a').forEach(a=>a.addEventListener('click',suspend));for(const type of['contextmenu','selectstart','dragstart'])document.addEventListener(type,e=>e.preventDefault());for(const type of['gesturestart','gesturechange','gestureend'])document.addEventListener(type,e=>{if(e.cancelable)e.preventDefault();},{passive:false});
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.045,(now-last)/1000);last=now;state.pulse=Math.max(0,state.pulse-dt*6);state.shake=Math.max(0,state.shake-dt*2);if(state.mode==='show'&&state.damage>=99.9&&(now-showStart)/1000>=(sound.lastSequence?.duration||6)*.86)detonate();world.update(dt,now/1000,state.pulse,state.damage);camera.position.copy(cameraBase);if(['show','settling'].includes(state.mode)){camera.position.x+=Math.sin(now*.00025)*.25;camera.position.z-=.2+state.damage*.003;state.tremor=state.mode==='show'?Math.pow(Math.min(1,(now-showStart)/1000/(sound.lastSequence?.duration||6)),2.4)*(2.3+state.stage*.6):0;const shaking=state.shake+world.quake*.55+state.tremor;camera.position.x+=Math.sin(now*.057)*shaking*.08;camera.position.y+=Math.sin(now*.066)*shaking*.05;camera.position.z+=Math.sin(now*.043)*shaking*.04;}camera.lookAt(target);renderer.render(world.scene,camera);}
window.addEventListener('pagehide',suspend);window.addEventListener('pageshow',e=>{if(e.persisted&&state.mode==='board')beginAmbient();});window.rockGame={state,sound,world,camera,renderer,perform,start,nextStage,install,calculate,levels:LEVELS,catalog,suspend};renderBoard();$('loading').hidden=true;requestAnimationFrame(animate);
