import {T,build} from './world.js?v=rock-1';
import {Sound} from './audio.js?v=rock-1';
const $=id=>document.getElementById(id),world=build(),sound=new Sound(),renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('scene').append(renderer.domElement);const camera=new T.PerspectiveCamera(44,1,.1,60),target=new T.Vector3(-.15,1.25,.25),cameraBase=new T.Vector3();
const catalog=[{id:'drive',name:'DRIVE',model:'IRON / OD-01',color:'#ca844c',cost:0,description:'溫暖的過載與更密實的重擊。強度越高，牆面碎得越乾脆。',label:'GAIN'},{id:'echo',name:'ECHO',model:'TAPE / D-03',color:'#9db6a7',cost:0,description:'附點八分音符回聲，讓 Riff 後面還有一波追擊。放在破音前後，會有不同的質感。',label:'REPEAT'},{id:'space',name:'SPACE',model:'ROOM / R-07',color:'#ad9ebb',cost:0,description:'短空間到大廳殘響。增加音浪範圍，房子像被聲音包住。',label:'ROOM'},{id:'fuzz',name:'FUZZ',model:'WOOL / F-02',color:'#cb6960',cost:700,description:'更粗糙、飽滿的削波失真。連鎖碎裂更猛烈。',label:'FUZZ'},{id:'eq',name:'DEPTH',model:'SHAPE / E-05',color:'#7c9da9',cost:950,description:'稍微推起厚度、挖掉混濁中頻。強化地基衝擊。',label:'DEPTH'},{id:'comp',name:'PRESS',model:'SUSTAIN / C-04',color:'#b5a675',cost:1200,description:'壓縮動態，讓音牆更持續。零碎磚塊也不放過。',label:'SUSTAIN'}];
let saved={money:0,owned:['drive','echo','space'],best:0,order:['drive','echo','space'],values:{}};try{const prior=JSON.parse(localStorage.getItem('qaf-rock-demolition-v1'));if(prior&&Number.isFinite(prior.money)&&prior.money>=0)saved={...saved,...prior};}catch{}const state={mode:'menu',damage:0,money:saved.money,owned:new Set(saved.owned),pedals:saved.order.slice(0,3).map((id,i)=>({id:catalog.some(p=>p.id===id)?id:catalog[i].id,amount:saved.values[id]?.amount??[72,58,63][i],on:saved.values[id]?.on??true})),variation:0,notes:0,earnings:0,editing:0,selectedSlot:0,pulse:0,shake:0,started:false};let last=performance.now(),disposed=false,pendingResult=0,drag=null,hasDragged=false;
function persist(){saved={money:state.money,owned:[...state.owned],best:Math.max(saved.best,state.damage),order:state.pedals.map(p=>p.id),values:Object.fromEntries(state.pedals.map(p=>[p.id,{amount:p.amount,on:p.on}]))};try{localStorage.setItem('qaf-rock-demolition-v1',JSON.stringify(saved));}catch{}}
function resize(){const w=$('scene').clientWidth,h=$('scene').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;const narrow=w/h<1.45;cameraBase.set(narrow?5.5:6.8,narrow?4.6:4.3,narrow?9.2:9.4);camera.position.copy(cameraBase);camera.lookAt(target);camera.updateProjectionMatrix();}function lockHeight(){document.documentElement.style.setProperty('--height',innerHeight+'px');}lockHeight();new ResizeObserver(resize).observe($('scene'));window.addEventListener('orientationchange',()=>setTimeout(()=>{lockHeight();resize();},250));resize();
function pedalDOM(p,i){const d=catalog.find(c=>c.id===p.id);return `<button class="pedal ${p.on?'':'off'}" data-slot="${i}" style="--paint:${d.color};--turn:${-135+p.amount*2.7}deg" aria-label="調整 ${d.name}，${p.amount}%，${p.on?'開啟':'關閉'}"><i class="screw">⊕</i><i class="screw right">⊕</i><div class="knobs"><i class="knob"></i><i class="knob small"></i></div><span class="knob-label">${d.label} / TONE</span><strong>${d.name}</strong><span class="model">${d.model}</span><i class="led"></i><i class="footswitch"></i><span class="value">${p.amount}%</span></button>`;}
function renderBoard(){ $('money').textContent=state.money.toLocaleString('zh-TW');$('pedals').innerHTML=state.pedals.map(pedalDOM).join('');$('chain-name').textContent=state.pedals.map(p=>catalog.find(c=>c.id===p.id).name).join(' → ');$('rack').innerHTML=catalog.map(p=>`<button class="rack-pedal ${state.owned.has(p.id)?'':'locked'} ${state.pedals.some(e=>e.id===p.id)?'selected':''}" data-id="${p.id}" style="--paint:${p.color}" aria-label="${state.owned.has(p.id)?'裝上':'購買'} ${p.name}${p.cost&&!state.owned.has(p.id)?'，'+p.cost+'元':''}"><i class="mini-pedal"></i><div><strong>${p.name}</strong><small>${state.owned.has(p.id)?state.pedals.some(e=>e.id===p.id)?'盤上使用中':'點選裝上':'$ '+p.cost}</small></div></button>`).join('');sound.route(state.pedals);persist();}
function edit(i){if(state.mode!=='board')return;state.editing=i;state.selectedSlot=i;const p=state.pedals[i],d=catalog.find(c=>c.id===p.id);$('edit-name').textContent=d.name;$('amount-label').textContent=d.label;$('edit-description').textContent=d.description;$('amount').value=p.amount;updateEdit();$('editor').showModal();}
function updateEdit(){const p=state.pedals[state.editing];$('amount-value').textContent=p.amount+'%';$('big-knob').style.transform=`rotate(${-135+p.amount*2.7}deg)`;$('bypass').textContent=p.on?'已開啟 ●':'旁通 ○';$('bypass').style.color=p.on?'#b4d7a3':'#a0a4a9';}
function install(id,slot=state.selectedSlot){if(state.mode!=='board')return;const d=catalog.find(c=>c.id===id);if(!state.owned.has(id)){if(state.money<d.cost){$('notice').textContent=`${d.name} 還差 $${d.cost-state.money}，先拆一棟！`;return;}state.money-=d.cost;state.owned.add(id);$('notice').textContent=`${d.name} 已入手！已裝上第 ${slot+1} 格。`;}else $('notice').textContent=`${d.name} 裝上第 ${slot+1} 格。`;const existing=state.pedals.findIndex(p=>p.id===id);if(existing>=0){[state.pedals[existing],state.pedals[slot]]=[state.pedals[slot],state.pedals[existing]];}else state.pedals[slot]={id,amount:70,on:true};state.selectedSlot=(slot+1)%3;renderBoard();}
function beginAmbient(){if(state.mode==='board'&&sound.enabled&&!document.hidden)sound.sequence({kind:'ambient',variation:3,onNote:n=>{state.pulse=n.accent?.3:.15;},onFinish:beginAmbient});}
async function start(){if($('start').disabled)return;$('start').disabled=true;$('again').disabled=true;$('load-status').textContent='真實樂器音色載入中…';try{await sound.preload();clearTimeout(pendingResult);world.reset();Object.assign(state,{mode:'board',damage:0,notes:0,earnings:0,pulse:0,shake:0});$('menu').hidden=true;$('end').hidden=true;$('riff-caption').hidden=true;$('perform').textContent='開彈拆房子 ↗';$('perform').disabled=false;$('audition').disabled=false;$('game').classList.remove('performing');$('damage').innerHTML='0<small>%</small>';$('damage-bar').style.width='0%';$('notice').textContent='轉旋鈕、踩開關。怎麼組都能拆。';renderBoard();window.QAFPlayCount?.start('rock-demolition');state.started=true;beginAmbient();}catch(e){sound.ready=null;$('load-status').textContent='音色載入失敗，請再按一次。';console.error(e);}finally{$('start').disabled=false;$('again').disabled=false;}}
function power(){return state.pedals.reduce((s,p)=>s+(p.on?({drive:.85,echo:.5,space:.36,fuzz:1.2,eq:.65,comp:.7}[p.id])*p.amount/100:0),1.05);}
function hit(n){state.pulse=n.accent?1:.65;if(state.mode!=='show')return;state.notes++;const current=power(),value=(n.accent?1.32:.84)*current;state.damage=Math.min(100,state.damage+value);world.damage(state.damage,current*.4);state.shake=n.accent?.8:.30;if(n.accent&&state.damage>25)sound.impact(.45);$('damage').innerHTML=Math.floor(state.damage)+'<small>%</small>';$('damage-bar').style.width=state.damage+'%';if(state.damage>=100&&!pendingResult){$('riff-caption').querySelector('strong').textContent='最後一擊，漂亮收工！';}}
async function perform(){if(state.mode!=='board')return;await sound.unlock();state.mode='show';state.variation=(state.variation+1)%4;$('game').classList.add('performing');$('perform').disabled=true;$('audition').disabled=true;$('editor').close();$('riff-caption').hidden=false;$('riff-caption').querySelector('strong').textContent='音量開大，房子放倒。';$('notice').textContent='正在拆除，讓這段 Riff 彈完。';sound.route(state.pedals);sound.sequence({kind:'show',variation:state.variation,onNote:hit,onFinish:()=>{if(state.damage>=99.9){state.mode='settling';pendingResult=setTimeout(finish,1350);}else{state.mode='board';$('game').classList.remove('performing');$('perform').disabled=false;$('audition').disabled=false;$('perform').textContent='再來一段！ ↗';$('riff-caption').hidden=true;$('notice').textContent='還有一點沒倒。換個組合，或再來一段！';beginAmbient();}}});}
function finish(){pendingResult=0;if(state.mode!=='settling')return;state.mode='end';const fee=650,bonus=Math.round(Math.max(0,power()-1)*180/10)*10;state.earnings=fee+bonus;state.money+=state.earnings;persist();$('result-percent').innerHTML=Math.round(state.damage)+'<small>%</small>';$('fee').textContent='$'+fee;$('bonus').textContent='$'+bonus;$('earned').textContent='$'+state.earnings.toLocaleString('zh-TW');$('best').textContent=`器材基金 $${state.money.toLocaleString('zh-TW')} · 裝置內最佳拆除 ${Math.round(saved.best)}%`;$('end').hidden=false;$('game').classList.remove('performing');sound.stop();sound.sequence({kind:'preview',variation:2,onNote:n=>state.pulse=n.accent?.35:.15});}
async function audition(){if(state.mode!=='board')return;await sound.unlock();$('audition').disabled=true;$('notice').textContent='試音中 · 效果器順序與旋鈕會改變聲音';sound.route(state.pedals);sound.sequence({kind:'preview',variation:state.variation,onNote:n=>state.pulse=n.accent?.8:.5,onFinish:()=>{$('audition').disabled=false;$('notice').textContent='這個音色，拿去拆一棟。';beginAmbient();}});}
$('start').onclick=start;$('again').onclick=start;$('perform').onclick=perform;$('audition').onclick=audition;$('reorder').onclick=()=>{if(state.mode!=='board')return;state.pedals.push(state.pedals.shift());renderBoard();$('notice').textContent='接線順序已改變，試聽看看。';};$('pedals').addEventListener('click',e=>{const p=e.target.closest('[data-slot]');if(p&&!hasDragged){const i=Number(p.dataset.slot);if(e.target.closest('.footswitch')){state.pedals[i].on=!state.pedals[i].on;renderBoard();}else edit(i);}});$('rack').addEventListener('click',e=>{const p=e.target.closest('[data-id]');if(p&&!hasDragged)install(p.dataset.id);});$('close-edit').onclick=()=> $('editor').close();$('editor').addEventListener('click',e=>{if(e.target===$('editor'))$('editor').close();});$('amount').oninput=()=>{state.pedals[state.editing].amount=Number($('amount').value);updateEdit();renderBoard();};$('bypass').onclick=()=>{const p=state.pedals[state.editing];p.on=!p.on;updateEdit();renderBoard();};
// Pointer drag is shared by mouse and touch. Tap is retained for small phones.
function dragStart(e){const node=e.target.closest('[data-slot], [data-id]');if(!node||state.mode!=='board')return;hasDragged=false;drag={node,slot:node.dataset.slot!==undefined?Number(node.dataset.slot):null,id:node.dataset.id,x:e.clientX,y:e.clientY,pointer:e.pointerId};node.setPointerCapture(e.pointerId);}
function dragMove(e){if(!drag||drag.pointer!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<9&&!hasDragged)return;hasDragged=true;drag.node.classList.add('dragging');document.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]')?.classList.add('drop-target');}
function dragEnd(e){if(!drag||drag.pointer!==e.pointerId)return;const node=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(hasDragged&&node){const slot=Number(node.dataset.slot);if(drag.id)install(drag.id,slot);else{[state.pedals[drag.slot],state.pedals[slot]]=[state.pedals[slot],state.pedals[drag.slot]];renderBoard();}}drag.node.classList.remove('dragging');document.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));drag=null;setTimeout(()=>hasDragged=false,120);}
for(const id of['pedals','rack']){$(id).addEventListener('pointerdown',dragStart);$(id).addEventListener('pointermove',dragMove);$(id).addEventListener('pointerup',dragEnd);$(id).addEventListener('pointercancel',e=>{if(drag){drag.node.classList.remove('dragging');drag=null;hasDragged=false;}});}
$('sound').onclick=async()=>{await sound.unlock();sound.enabled=!sound.enabled;$('sound').textContent=sound.enabled?'♫ ON':'♫ OFF';if(!sound.enabled){sound.master.gain.value=0;}else{sound.master.gain.value=.63;if(state.mode==='board'&&!sound.clock)beginAmbient();}};
function suspend(){sound.stop();clearTimeout(pendingResult);pendingResult=0;if(state.mode==='show'||state.mode==='settling'){state.mode='board';$('game').classList.remove('performing');$('perform').disabled=false;$('audition').disabled=false;$('perform').textContent='繼續開彈 ↗';$('riff-caption').hidden=true;$('notice').textContent='演奏已暫停，按開彈繼續。';}else if(state.mode==='board')$('audition').disabled=false;}
document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();else if(state.mode==='board')beginAmbient();});document.querySelectorAll('a').forEach(a=>a.addEventListener('click',suspend));for(const type of['contextmenu','selectstart','dragstart'])document.addEventListener(type,e=>e.preventDefault());for(const type of['gesturestart','gesturechange','gestureend'])document.addEventListener(type,e=>{if(e.cancelable)e.preventDefault();},{passive:false});
function animate(now){if(disposed)return;requestAnimationFrame(animate);const dt=Math.min(.045,(now-last)/1000);last=now;state.pulse=Math.max(0,state.pulse-dt*6);state.shake=Math.max(0,state.shake-dt*4);world.update(dt,now/1000,state.pulse,state.damage);camera.position.copy(cameraBase);if(state.mode==='show'){const t=Math.sin(now*.00025);camera.position.x+=t*.3;camera.position.z-=.2+state.damage*.003;camera.position.x+=Math.sin(now*.057)*state.shake*.032;camera.position.y+=Math.sin(now*.066)*state.shake*.02;}camera.lookAt(target);renderer.render(world.scene,camera);}
window.addEventListener('pagehide',()=>{suspend();});window.addEventListener('pageshow',e=>{if(e.persisted&&state.mode==='board')beginAmbient();});window.rockGame={state,sound,world,camera,renderer,perform,start,install,power,suspend};renderBoard();$('loading').hidden=true;requestAnimationFrame(animate);

