'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui=id=>document.getElementById(id),palettes=[['#252039','#ffdd68','#ab88e6'],['#12343c','#6bffda','#ff87ac'],['#381d30','#ff8d64','#b6a1ff']];
let W=390,H=800,level=0,combo=0,mode='menu',time=0,last=0,phase=0,stageTime=0,slowWindow=false,poseIndex=-1,shot=null,reveal=0,explosion=0,particles=[],aim={x:0,y:0},joy={x:0,y:0},keys={},audio=null,sound=true;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;canvas.width=W*devicePixelRatio;canvas.height=H*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}window.addEventListener('resize',resize);resize();
const poses=[{name:'孔雀開屏',body:-.2,left:.3,right:-.5,bob:9},{name:'腋下有風',body:.3,left:1.3,right:-1.4,bob:6},{name:'西裝游泳',body:-.4,left:-.7,right:.9,bob:12},{name:'我最閃亮',body:.45,left:.8,right:-.2,bob:7},{name:'華麗歪腰',body:-.6,left:1.6,right:.4,bob:10},{name:'領帶起飛',body:.1,left:-1.2,right:-1.1,bob:14},{name:'狗狗芭蕾',body:.55,left:1.9,right:-1.9,bob:11},{name:'嘶～迪斯可',body:-.3,left:1,right:1.4,bob:13}];
function nextPose(){const n=Math.floor(Math.random()*(poses.length-1));poseIndex=poseIndex<0?Math.floor(Math.random()*poses.length):(poseIndex+1+n)%poses.length}
function swaySpeed(){return level===2?(stageTime%6.2>=2.6&&stageTime%6.2<4.6?.6:3.3):[1.5,2.5][level]}
function port(){const headerBottom=document.querySelector('header').getBoundingClientRect().bottom-canvas.getBoundingClientRect().top;const tvHeight=Math.min(H*.235,W*.51);return{x:W/2,y:Math.max(headerBottom+18,H*.21)+tvHeight+28}}function tip(){const p=port();let dx=aim.x+Math.sin(phase*2.1)*[18,24,31][level]+Math.sin(phase*4.2)*7,dy=aim.y+Math.sin(phase*2.1)*[9,12,15][level];const cycle=stageTime%6.2;if(level===2&&cycle>=2.6&&cycle<4.6){const t=cycle-2.6;const edge=clamp(Math.min(t,2-t)/.3,0,1),blend=edge*edge*(3-2*edge);const guidedX=Math.sin((t-1)*1.1)*18+joy.x*10,guidedY=Math.sin((t-1)*.8)*8+joy.y*6;dx=dx*(1-blend)+guidedX*blend;dy=dy*(1-blend)+guidedY*blend;}return{x:p.x+dx,y:p.y+dy}}
function tone(freq,duration=.1,type='sine'){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
const soundBuffers={},soundFiles={success:'audio/success-tight.wav',miss:'audio/miss.mp3'};let voiceSource=null;
const soundData=Object.fromEntries(Object.entries(soundFiles).map(([name,url])=>[name,fetch(url).then(r=>{if(!r.ok)throw Error('Sound unavailable');return r.arrayBuffer()}).catch(()=>null)]));
function shortenSuccessPause(buffer){const sr=buffer.sampleRate,gapStart=1.04,gapEnd=2.28,gap=gapEnd-gapStart;const cutStart=Math.round((gapStart+gap/6)*sr),cutEnd=Math.round((gapEnd-gap/6)*sr);if(buffer.duration<gapEnd)return buffer;const result=audio.createBuffer(buffer.numberOfChannels,buffer.length-(cutEnd-cutStart),sr);for(let channel=0;channel<buffer.numberOfChannels;channel++){const source=buffer.getChannelData(channel),target=result.getChannelData(channel);target.set(source.subarray(0,cutStart));target.set(source.subarray(cutEnd),cutStart)}return result}
function unlockAudio(){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});for(const name of Object.keys(soundData)){if(soundBuffers[name])continue;soundBuffers[name]='loading';soundData[name].then(data=>data?audio.decodeAudioData(data.slice(0)):null).then(buffer=>soundBuffers[name]=buffer).catch(()=>soundBuffers[name]=null)}}
function playVoice(name){if(!sound||!audio)return;const buffer=soundBuffers[name];if(!buffer||buffer==='loading'){tone(name==='success'?880:85,.15);return}if(voiceSource){try{voiceSource.stop()}catch{}}const source=audio.createBufferSource(),gain=audio.createGain();source.buffer=buffer;gain.gain.value=.7;source.connect(gain).connect(audio.destination);source.start();voiceSource=source;source.onended=()=>{if(voiceSource===source)voiceSource=null}}
function fanfare(){if(!sound||!audio)return;const now=audio.currentTime;[0,.24].forEach((delay,index)=>{[1,1.25,1.5].forEach(ratio=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sawtooth';o.frequency.value=(index?440:349.23)*ratio;const t=now+delay;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.035,t+.012);g.gain.setValueAtTime(.035,t+.13);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.21)})})}
ui('sound').textContent='音效 ON';ui('sound').onclick=()=>{sound=!sound;if(sound){unlockAudio();tone(550)}else if(voiceSource){try{voiceSource.stop()}catch{}}ui('sound').textContent='音效 '+(sound?'ON':'OFF')};

function hud(){ui('level').textContent=`STAGE 0${level+1} / 03`;ui('combo').textContent=Array.from({length:5},(_,i)=>i<combo?'●':'○').join(' ')}
function start(){level=0;begin()}function begin(){combo=0;mode='play';stageTime=0;slowWindow=false;phase=0;shot=null;reveal=0;explosion=0;aim={x:0,y:0};particles=[];ui('overlay').style.display='none';ui('hint').textContent=['抓準時機，讓狗狗華麗登場。','手更晃了！對準就插！','最後一關！等突然慢下來，再出手！'][level];hud()}
ui('start').onclick=()=>{if(sound)unlockAudio();if(mode==='clear'){level++;begin()}else start()};
function fire(){if(mode!=='play'||shot)return;const t=tip(),p=port();shot={x:t.x,y:t.y,elapsed:0,hit:Math.abs(t.x-p.x)<15&&Math.abs(t.y-p.y)<11,resolved:false};tone(180,.12,'sawtooth')}
ui('fire').addEventListener('pointerdown',e=>{e.preventDefault();fire()});
window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(!e.repeat)fire()}});window.addEventListener('blur',()=>last=0);document.addEventListener('visibilitychange',()=>last=0);
function round(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}}
function path(points,fill,stroke='#171421',width=3){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}}
function text(s,x,y,size,color='#fff',rotation=0){ctx.save();ctx.translate(x,y);ctx.rotate(rotation);ctx.font=`900 ${size}px system-ui`;ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(s,0,0);ctx.restore()}
function star(x,y,r,color){ctx.save();ctx.translate(x,y);path(Array.from({length:16},(_,i)=>{const a=i*Math.PI/8;return[Math.cos(a)*(i%2?r*.48:r),Math.sin(a)*(i%2?r*.48:r)]}),color);ctx.restore()}
function character(x,y,w,h){ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();const c=palettes[level];ctx.fillStyle=c[2];ctx.fillRect(x,y,w,h);for(let i=0;i<20;i++){ctx.strokeStyle='#fff5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+w/2,y+h/2);ctx.lineTo(x+w/2+Math.cos(i)*w*2,y+h/2+Math.sin(i)*h*2);ctx.stroke()}const pose=poses[Math.max(0,poseIndex)];const dance=Math.sin((1.5-reveal)*14);ctx.translate(x+w/2,y+h*.51+dance*pose.bob);ctx.scale(w/260,h/180);ctx.rotate(pose.body+dance*.07);path([[-38,27],[-68,65],[-49,150],[55,150],[66,58],[33,27]],'#efe6da');path([[-38,27],[-68,65],[-49,150],[-8,150],[-17,43]],'#352441');path([[33,27],[66,58],[55,150],[4,150],[17,43]],'#352441');path([[-12,36],[0,49],[12,36],[6,110],[-6,110]],c[1]);ctx.save();ctx.rotate(pose.left+dance*.17);round(-104,32,75,24,10,'#352441','#171421');round(-119,28,25,26,9,'#d9a15f','#171421');ctx.restore();ctx.save();ctx.rotate(pose.right-dance*.17);round(30,30,93,24,10,'#352441','#171421');round(111,24,26,30,9,'#d9a15f','#171421');ctx.restore();path([[-32,-52],[-50,-63],[-64,-35],[-62,15],[-43,23],[-33,-4]],'#805432');path([[32,-52],[50,-63],[64,-35],[62,15],[43,23],[33,-4]],'#805432');round(-36,-60,72,91,28,'#d9a15f','#171421');path([[-12,-59],[10,-59],[16,-32],[8,-8],[-7,-8],[-16,-32]],'#f8dfb2',null);round(-35,-36,33,20,6,'#fbf2d3','#171421');round(2,-36,33,20,6,'#fbf2d3','#171421');ctx.strokeStyle='#171421';ctx.beginPath();ctx.moveTo(-2,-29);ctx.lineTo(2,-29);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-28,-20);ctx.lineTo(-12,-32);ctx.moveTo(8,-20);ctx.lineTo(24,-32);ctx.stroke();ctx.beginPath();ctx.ellipse(0,7,27,21,0,0,Math.PI*2);ctx.fillStyle='#f8dfb2';ctx.fill();ctx.strokeStyle='#171421';ctx.lineWidth=3;ctx.stroke();round(-7,15,14,22,7,'#f58c9e','#171421');path([[-12,-1],[12,-1],[8,9],[0,13],[-8,9]],'#25202a');ctx.beginPath();ctx.moveTo(0,11);ctx.lineTo(0,18);ctx.moveTo(-17,13);ctx.quadraticCurveTo(-9,23,0,18);ctx.quadraticCurveTo(9,23,17,13);ctx.strokeStyle='#171421';ctx.lineWidth=2;ctx.stroke();ctx.restore();text('啊～～～～嘶～～',x+w*.5,y+h*.85,23,'#fff');text(pose.name,x+w*.5,y+h*.97,11,c[1]);star(x+w*.87,y+h*.21,14,c[1]);}
function hand(x,y,progress){ctx.save();ctx.translate(x,y);ctx.scale(1+progress*.36,1+progress*.36);ctx.strokeStyle='#171421';ctx.lineWidth=15;ctx.beginPath();ctx.moveTo(0,55);ctx.bezierCurveTo(-25,130,65,180,28,310);ctx.stroke();path([[4,240],[-12,100],[-27,69],[-24,35],[-12,27],[20,33],[39,61],[55,240]],'#df9e7c');round(-27,29,48,51,15,'#efb794','#171421');round(-17,44,43,18,9,'#efb794','#171421');round(-17,62,43,16,8,'#efb794','#171421');round(-16,13,32,41,6,'#34313c','#171421');path([[-18,0],[18,0],[18,12],[12,20],[-12,20],[-18,12]],'#d3d6dd');round(-12,3,24,7,1,'#8d8c96');for(let i=0;i<7;i++){ctx.fillStyle='#dabd72';ctx.fillRect(-10+i*3,5,1,3)}text('HDMI',0,34,7,'#aaa');ctx.restore()}
function impact(x,y){ctx.save();ctx.translate(x,y);ctx.rotate(-.15);const points=Array.from({length:24},(_,i)=>{let a=i*Math.PI/12,r=i%2?31:50+(i%3)*9;return[Math.cos(a)*r,Math.sin(a)*r*.7]});path(points,'#ffe56c','#171421',4);ctx.scale(.88,.88);path(points,'#fff','#171421',2);text('咚！',0,8,23,'#211e35');ctx.restore()}
function finish(){fanfare();mode=level===2?'win':'clear';ui('overlay').style.display='grid';ui('title').textContent=level===2?'HDMI 大師！':'電視炸啦！';ui('description').innerHTML=level===2?'🎟️ <strong>HDMI 折價券</strong><br>請找阿呆換購<br><small>你已完成三關，插入傳說由你締造。</small>':`第 ${level+1} 關過關！<br>連續五次華麗插入。<br>下一關，手會晃得更快！`;ui('start').textContent=level===2?'再玩一次 →':'挑戰下一關 →'}
function update(dt){time+=dt;if(mode==='play'){stageTime+=dt;const slow=level===2&&swaySpeed()<1;if(slow!==slowWindow){slowWindow=slow;if(!reveal)ui('hint').textContent=slow?'慢動作空檔！就是現在，插！':'手速恢復！下一個空檔快來了。'}}phase+=dt*swaySpeed();reveal=Math.max(0,reveal-dt);if(shot){shot.elapsed+=dt;if(shot.elapsed>=.13&&!shot.resolved){shot.resolved=true;if(shot.hit){combo++;nextPose();reveal=1.5;playVoice('success');ui('hint').textContent=poses[poseIndex].name+'！啊～～～～嘶～～ ✨';if(combo===5){mode='explode';explosion=.95;const p=port();particles=Array.from({length:65},()=>({x:p.x,y:p.y-80,vx:(Math.random()-.5)*550,vy:(Math.random()-.65)*550,r:3+Math.random()*15}));tone(65,.55,'sawtooth')}}else{combo=0;playVoice('miss');ui('hint').textContent='咚！連擊歸零，再來一次！';if(navigator.vibrate)navigator.vibrate(35)}hud()}if(shot.elapsed>(shot.hit?.46:.36))shot=null}if(mode==='explode'){explosion-=dt;particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt});if(explosion<=0)finish()}}
function draw(){const c=palettes[level],p=port();ctx.fillStyle=c[0];ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffff04';for(let y=0;y<H;y+=24)for(let x=0;x<W;x+=24){ctx.beginPath();ctx.arc(x,y,1,0,7);ctx.fill()}const glow=ctx.createRadialGradient(W/2,H*.36,10,W/2,H*.36,W*.7);glow.addColorStop(0,c[2]+'38');glow.addColorStop(1,c[0]+'00');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);const tw=W*.8,th=Math.min(H*.235,W*.51),tx=(W-tw)/2,ty=p.y-th-28;if(mode!=='explode'){round(tx+12,ty+15,tw,th+44,18,'#0004');round(tx,ty,tw,th+38,16,'#4c4958','#15121e');round(tx+10,ty+10,tw-20,th-6,8,'#07080e','#15121e');if(reveal>0)character(tx+14,ty+14,tw-28,th-14);else{ctx.fillStyle='#ffffff04';ctx.beginPath();ctx.moveTo(tx+13,ty+13);ctx.lineTo(tx+tw*.65,ty+13);ctx.lineTo(tx+13,ty+th*.8);ctx.fill();text('NO SIGNAL',W/2,ty+th*.55,12,'#45434f')}round(p.x-23,p.y-10,46,20,4,'#15121e','#a4a1ae');path([[p.x-18,p.y-6],[p.x+18,p.y-6],[p.x+14,p.y+6],[p.x-14,p.y+6]],'#62616c',null);round(p.x-13,p.y-2,26,4,1,'#191722');ctx.fillStyle=c[1];ctx.beginPath();ctx.arc(tx+tw-18,ty+th+20,2,0,7);ctx.fill()}else{particles.forEach((q,i)=>{ctx.save();ctx.translate(q.x,q.y);ctx.rotate(time*(i%2?5:-5));ctx.fillStyle=i%3===0?c[1]:i%3===1?c[2]:'#fff';ctx.fillRect(-q.r/2,-q.r/2,q.r,q.r);ctx.restore()});star(W/2,p.y-70,Math.max(10,120*explosion),c[1]);text('BOOOM!',W/2,p.y-65,38,'#211e35',-.1)}
let t=shot?{x:shot.x,y:shot.y}:tip(),progress=0;if(shot){progress=shot.elapsed<.13?shot.elapsed/.13:shot.elapsed<.23?1:Math.max(0,1-(shot.elapsed-.23)/.13);for(let i=0;i<14;i++){const a=i/14*Math.PI*2;ctx.strokeStyle=c[1]+'90';ctx.lineWidth=1+i%3;ctx.beginPath();ctx.moveTo(t.x+Math.cos(a)*65,t.y+Math.sin(a)*80);ctx.lineTo(t.x+Math.cos(a)*(100+progress*100),t.y+Math.sin(a)*(120+progress*100));ctx.stroke()}}const offset=(1-progress)*H*.17;hand(t.x,t.y+offset,progress);if(!shot&&mode==='play'){ctx.strokeStyle=Math.abs(t.x-p.x)<15&&Math.abs(t.y-p.y)<11?'#86ffd5':'#fff7';ctx.lineWidth=1;ctx.beginPath();ctx.arc(t.x,t.y,8,0,Math.PI*2);ctx.moveTo(t.x-12,t.y);ctx.lineTo(t.x+12,t.y);ctx.moveTo(t.x,t.y-12);ctx.lineTo(t.x,t.y+12);ctx.stroke();text('對準這裡 ↑',W/2,p.y+37,10,'#a9a1ba')}if(shot&&!shot.hit&&shot.elapsed>=.13&&shot.elapsed<.23)impact(t.x,t.y);if(reveal>0&&mode==='play')text('華麗插入！',W/2,H*.62,23,c[1],-.08)}
function frame(ms){const dt=last?Math.min((ms-last)/1000,.04):0;last=ms;update(dt);draw();requestAnimationFrame(frame)}hud();requestAnimationFrame(frame);